/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type {
  UsersPermissionsDeleteRolesByRole200,
  UsersPermissionsDeleteUsersById200,
  UsersPermissionsGetAuthByProviderCallback200,
  UsersPermissionsGetPermissions200,
  UsersPermissionsGetRoles200,
  UsersPermissionsGetRolesById200,
  UsersPermissionsGetUsers200Item,
  UsersPermissionsGetUsersById200,
  UsersPermissionsGetUsersByIdParams,
  UsersPermissionsGetUsersCountParams,
  UsersPermissionsGetUsersMe200,
  UsersPermissionsGetUsersMeParams,
  UsersPermissionsGetUsersParams,
  UsersPermissionsPostAuthChangePassword200,
  UsersPermissionsPostAuthChangePasswordBody,
  UsersPermissionsPostAuthForgotPassword200,
  UsersPermissionsPostAuthForgotPasswordBody,
  UsersPermissionsPostAuthLocal200,
  UsersPermissionsPostAuthLocalBody,
  UsersPermissionsPostAuthLocalRegister200,
  UsersPermissionsPostAuthLocalRegisterBody,
  UsersPermissionsPostAuthResetPassword200,
  UsersPermissionsPostAuthResetPasswordBody,
  UsersPermissionsPostAuthSendEmailConfirmation200,
  UsersPermissionsPostAuthSendEmailConfirmationBody,
  UsersPermissionsPostRoles200,
  UsersPermissionsPostRolesBody,
  UsersPermissionsPostUsers200,
  UsersPermissionsPostUsersBody,
  UsersPermissionsPutRolesByRole200,
  UsersPermissionsPutRolesByRoleBody,
  UsersPermissionsPutUsersById200,
  UsersPermissionsPutUsersByIdBody,
} from "../learningStrapiV5.schemas";

import { strapiClient } from "../../../lib/strapi-client";

export const getUsersPermissions = () => {
  const usersPermissionsGetConnect = () => {
    return strapiClient<unknown>({ url: `/connect/(.*)`, method: "GET" });
  };
  const usersPermissionsPostAuthLocal = (
    usersPermissionsPostAuthLocalBody: UsersPermissionsPostAuthLocalBody,
  ) => {
    return strapiClient<UsersPermissionsPostAuthLocal200>({
      url: `/auth/local`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: usersPermissionsPostAuthLocalBody,
    });
  };
  const usersPermissionsPostAuthLocalRegister = (
    usersPermissionsPostAuthLocalRegisterBody: UsersPermissionsPostAuthLocalRegisterBody,
  ) => {
    return strapiClient<UsersPermissionsPostAuthLocalRegister200>({
      url: `/auth/local/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: usersPermissionsPostAuthLocalRegisterBody,
    });
  };
  const usersPermissionsGetAuthByProviderCallback = (provider: string) => {
    return strapiClient<UsersPermissionsGetAuthByProviderCallback200>({
      url: `/auth/${provider}/callback`,
      method: "GET",
    });
  };
  const usersPermissionsPostAuthForgotPassword = (
    usersPermissionsPostAuthForgotPasswordBody: UsersPermissionsPostAuthForgotPasswordBody,
  ) => {
    return strapiClient<UsersPermissionsPostAuthForgotPassword200>({
      url: `/auth/forgot-password`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: usersPermissionsPostAuthForgotPasswordBody,
    });
  };
  const usersPermissionsPostAuthResetPassword = (
    usersPermissionsPostAuthResetPasswordBody: UsersPermissionsPostAuthResetPasswordBody,
  ) => {
    return strapiClient<UsersPermissionsPostAuthResetPassword200>({
      url: `/auth/reset-password`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: usersPermissionsPostAuthResetPasswordBody,
    });
  };
  const usersPermissionsGetAuthEmailConfirmation = () => {
    return strapiClient<unknown>({
      url: `/auth/email-confirmation`,
      method: "GET",
    });
  };
  const usersPermissionsPostAuthSendEmailConfirmation = (
    usersPermissionsPostAuthSendEmailConfirmationBody: UsersPermissionsPostAuthSendEmailConfirmationBody,
  ) => {
    return strapiClient<UsersPermissionsPostAuthSendEmailConfirmation200>({
      url: `/auth/send-email-confirmation`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: usersPermissionsPostAuthSendEmailConfirmationBody,
    });
  };
  const usersPermissionsPostAuthChangePassword = (
    usersPermissionsPostAuthChangePasswordBody: UsersPermissionsPostAuthChangePasswordBody,
  ) => {
    return strapiClient<UsersPermissionsPostAuthChangePassword200>({
      url: `/auth/change-password`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: usersPermissionsPostAuthChangePasswordBody,
    });
  };
  const usersPermissionsPostAuthRefresh = () => {
    return strapiClient<unknown>({ url: `/auth/refresh`, method: "POST" });
  };
  const usersPermissionsPostAuthLogout = () => {
    return strapiClient<unknown>({ url: `/auth/logout`, method: "POST" });
  };
  const usersPermissionsGetUsersCount = (
    params?: UsersPermissionsGetUsersCountParams,
  ) => {
    return strapiClient<number>({ url: `/users/count`, method: "GET", params });
  };
  const usersPermissionsGetUsers = (
    params?: UsersPermissionsGetUsersParams,
  ) => {
    return strapiClient<UsersPermissionsGetUsers200Item[]>({
      url: `/users`,
      method: "GET",
      params,
    });
  };
  const usersPermissionsPostUsers = (
    usersPermissionsPostUsersBody: UsersPermissionsPostUsersBody,
  ) => {
    return strapiClient<UsersPermissionsPostUsers200>({
      url: `/users`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: usersPermissionsPostUsersBody,
    });
  };
  const usersPermissionsGetUsersMe = (
    params?: UsersPermissionsGetUsersMeParams,
  ) => {
    return strapiClient<UsersPermissionsGetUsersMe200>({
      url: `/users/me`,
      method: "GET",
      params,
    });
  };
  const usersPermissionsGetUsersById = (
    id: string,
    params?: UsersPermissionsGetUsersByIdParams,
  ) => {
    return strapiClient<UsersPermissionsGetUsersById200>({
      url: `/users/${id}`,
      method: "GET",
      params,
    });
  };
  const usersPermissionsPutUsersById = (
    id: string,
    usersPermissionsPutUsersByIdBody: UsersPermissionsPutUsersByIdBody,
  ) => {
    return strapiClient<UsersPermissionsPutUsersById200>({
      url: `/users/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: usersPermissionsPutUsersByIdBody,
    });
  };
  const usersPermissionsDeleteUsersById = (id: string) => {
    return strapiClient<UsersPermissionsDeleteUsersById200>({
      url: `/users/${id}`,
      method: "DELETE",
    });
  };
  const usersPermissionsGetRolesById = (id: string) => {
    return strapiClient<UsersPermissionsGetRolesById200>({
      url: `/roles/${id}`,
      method: "GET",
    });
  };
  const usersPermissionsGetRoles = () => {
    return strapiClient<UsersPermissionsGetRoles200>({
      url: `/roles`,
      method: "GET",
    });
  };
  const usersPermissionsPostRoles = (
    usersPermissionsPostRolesBody: UsersPermissionsPostRolesBody,
  ) => {
    return strapiClient<UsersPermissionsPostRoles200>({
      url: `/roles`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: usersPermissionsPostRolesBody,
    });
  };
  const usersPermissionsPutRolesByRole = (
    role: string,
    usersPermissionsPutRolesByRoleBody: UsersPermissionsPutRolesByRoleBody,
  ) => {
    return strapiClient<UsersPermissionsPutRolesByRole200>({
      url: `/roles/${role}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: usersPermissionsPutRolesByRoleBody,
    });
  };
  const usersPermissionsDeleteRolesByRole = (role: string) => {
    return strapiClient<UsersPermissionsDeleteRolesByRole200>({
      url: `/roles/${role}`,
      method: "DELETE",
    });
  };
  const usersPermissionsGetPermissions = () => {
    return strapiClient<UsersPermissionsGetPermissions200>({
      url: `/permissions`,
      method: "GET",
    });
  };
  return {
    usersPermissionsGetConnect,
    usersPermissionsPostAuthLocal,
    usersPermissionsPostAuthLocalRegister,
    usersPermissionsGetAuthByProviderCallback,
    usersPermissionsPostAuthForgotPassword,
    usersPermissionsPostAuthResetPassword,
    usersPermissionsGetAuthEmailConfirmation,
    usersPermissionsPostAuthSendEmailConfirmation,
    usersPermissionsPostAuthChangePassword,
    usersPermissionsPostAuthRefresh,
    usersPermissionsPostAuthLogout,
    usersPermissionsGetUsersCount,
    usersPermissionsGetUsers,
    usersPermissionsPostUsers,
    usersPermissionsGetUsersMe,
    usersPermissionsGetUsersById,
    usersPermissionsPutUsersById,
    usersPermissionsDeleteUsersById,
    usersPermissionsGetRolesById,
    usersPermissionsGetRoles,
    usersPermissionsPostRoles,
    usersPermissionsPutRolesByRole,
    usersPermissionsDeleteRolesByRole,
    usersPermissionsGetPermissions,
  };
};
export type UsersPermissionsGetConnectResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsGetConnect"]
    >
  >
>;
export type UsersPermissionsPostAuthLocalResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsPostAuthLocal"]
    >
  >
>;
export type UsersPermissionsPostAuthLocalRegisterResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getUsersPermissions
      >["usersPermissionsPostAuthLocalRegister"]
    >
  >
>;
export type UsersPermissionsGetAuthByProviderCallbackResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getUsersPermissions
      >["usersPermissionsGetAuthByProviderCallback"]
    >
  >
>;
export type UsersPermissionsPostAuthForgotPasswordResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getUsersPermissions
      >["usersPermissionsPostAuthForgotPassword"]
    >
  >
>;
export type UsersPermissionsPostAuthResetPasswordResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getUsersPermissions
      >["usersPermissionsPostAuthResetPassword"]
    >
  >
>;
export type UsersPermissionsGetAuthEmailConfirmationResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getUsersPermissions
      >["usersPermissionsGetAuthEmailConfirmation"]
    >
  >
>;
export type UsersPermissionsPostAuthSendEmailConfirmationResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getUsersPermissions
      >["usersPermissionsPostAuthSendEmailConfirmation"]
    >
  >
>;
export type UsersPermissionsPostAuthChangePasswordResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getUsersPermissions
      >["usersPermissionsPostAuthChangePassword"]
    >
  >
>;
export type UsersPermissionsPostAuthRefreshResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsPostAuthRefresh"]
    >
  >
>;
export type UsersPermissionsPostAuthLogoutResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsPostAuthLogout"]
    >
  >
>;
export type UsersPermissionsGetUsersCountResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsGetUsersCount"]
    >
  >
>;
export type UsersPermissionsGetUsersResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsGetUsers"]
    >
  >
>;
export type UsersPermissionsPostUsersResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsPostUsers"]
    >
  >
>;
export type UsersPermissionsGetUsersMeResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsGetUsersMe"]
    >
  >
>;
export type UsersPermissionsGetUsersByIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsGetUsersById"]
    >
  >
>;
export type UsersPermissionsPutUsersByIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsPutUsersById"]
    >
  >
>;
export type UsersPermissionsDeleteUsersByIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsDeleteUsersById"]
    >
  >
>;
export type UsersPermissionsGetRolesByIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsGetRolesById"]
    >
  >
>;
export type UsersPermissionsGetRolesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsGetRoles"]
    >
  >
>;
export type UsersPermissionsPostRolesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsPostRoles"]
    >
  >
>;
export type UsersPermissionsPutRolesByRoleResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsPutRolesByRole"]
    >
  >
>;
export type UsersPermissionsDeleteRolesByRoleResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getUsersPermissions
      >["usersPermissionsDeleteRolesByRole"]
    >
  >
>;
export type UsersPermissionsGetPermissionsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsersPermissions>["usersPermissionsGetPermissions"]
    >
  >
>;
