/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetComponentsByUid200DataSchema } from "./contentTypeBuilderGetComponentsByUid200DataSchema";

export type ContentTypeBuilderGetComponentsByUid200Data = {
  /** @pattern ^[\w-]+\.[\w-]+$ */
  uid: string;
  category: string;
  apiId: string;
  schema: ContentTypeBuilderGetComponentsByUid200DataSchema;
};
