/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfEightPluginOptions } from "./contentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfEightPluginOptions";

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfEight =
  {
    type: "dynamiczone";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfEightPluginOptions;
    components: string[];
    required?: boolean;
    min?: number;
    max?: number;
  };
