/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetComponents200DataItem } from "./contentTypeBuilderGetComponents200DataItem";

export type ContentTypeBuilderGetComponents200 = {
  data: ContentTypeBuilderGetComponents200DataItem[];
};
