/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfSixPluginOptions } from "./contentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfSixPluginOptions";

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfSix =
  {
    type: "component";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfSixPluginOptions;
    component: string;
    repeatable: boolean;
    required?: boolean;
    min?: number;
    max?: number;
  };
