/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfThreePluginOptions } from "./contentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfThreePluginOptions";
import type { ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfThreeTargetAttribute } from "./contentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfThreeTargetAttribute";

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfThree =
  {
    type: "relation";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfThreePluginOptions;
    relation: string;
    /** @pattern ^((strapi|admin)::[\w-]+|(api|plugin)::[\w-]+\.[\w-]+)$ */
    target: string;
    targetAttribute: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfThreeTargetAttribute;
    autoPopulate?: boolean;
    mappedBy?: string;
    inversedBy?: string;
  };
