/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfThreePluginOptions } from "./contentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfThreePluginOptions";
import type { ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfThreeTargetAttribute } from "./contentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfThreeTargetAttribute";

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfThree =
  {
    type: "relation";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfThreePluginOptions;
    relation: string;
    /** @pattern ^((strapi|admin)::[\w-]+|(api|plugin)::[\w-]+\.[\w-]+)$ */
    target: string;
    targetAttribute: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfThreeTargetAttribute;
    autoPopulate?: boolean;
    mappedBy?: string;
    inversedBy?: string;
  };
