/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnezeroPluginOptions } from "./contentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnezeroPluginOptions";

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnezero =
  {
    type: "uid";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnezeroPluginOptions;
    targetField?: string;
  };
