/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwoMin } from "./contentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwoMin";
import type { ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwoMax } from "./contentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwoMax";
import type { ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwoPluginOptions } from "./contentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwoPluginOptions";

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwo =
  {
    type: string;
    required?: boolean;
    unique?: boolean;
    default?: unknown;
    min?: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwoMin;
    max?: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwoMax;
    minLength?: number;
    maxLength?: number;
    enum?: string[];
    regex?: string;
    private?: boolean;
    configurable?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwoPluginOptions;
  };
