/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThreePluginOptions } from "./contentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThreePluginOptions";
import type { ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThreeTargetAttribute } from "./contentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThreeTargetAttribute";

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThree =
  {
    type: "relation";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThreePluginOptions;
    relation: string;
    /** @pattern ^((strapi|admin)::[\w-]+|(api|plugin)::[\w-]+\.[\w-]+)$ */
    target: string;
    targetAttribute: ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThreeTargetAttribute;
    autoPopulate?: boolean;
    mappedBy?: string;
    inversedBy?: string;
  };
