/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetContentTypes200DataItemSchema } from "./contentTypeBuilderGetContentTypes200DataItemSchema";

export type ContentTypeBuilderGetContentTypes200DataItem = {
  /** @pattern ^((strapi|admin)::[\w-]+|(api|plugin)::[\w-]+\.[\w-]+)$ */
  uid: string;
  plugin?: string;
  apiID: string;
  schema: ContentTypeBuilderGetContentTypes200DataItemSchema;
};
