/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfPluginOptions } from "./contentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfPluginOptions";

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOf =
  {
    type: "media";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfPluginOptions;
    multiple: boolean;
    required?: boolean;
    allowedTypes?: string[];
  };
