/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOf } from "./contentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOf";
import type { ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThree } from "./contentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThree";
import type { ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfSix } from "./contentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfSix";
import type { ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfEight } from "./contentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfEight";
import type { ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnezero } from "./contentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnezero";
import type { ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwo } from "./contentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwo";

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributes = {
  [key: string]:
    | ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOf
    | ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThree
    | ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfSix
    | ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfEight
    | ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnezero
    | ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwo;
};
