/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwoMin } from "./contentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwoMin";
import type { ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwoMax } from "./contentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwoMax";
import type { ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwoPluginOptions } from "./contentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwoPluginOptions";

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwo =
  {
    type: string;
    required?: boolean;
    unique?: boolean;
    default?: unknown;
    min?: ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwoMin;
    max?: ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwoMax;
    minLength?: number;
    maxLength?: number;
    enum?: string[];
    regex?: string;
    private?: boolean;
    configurable?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwoPluginOptions;
  };
