/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwoMin } from "./contentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwoMin";
import type { ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwoMax } from "./contentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwoMax";
import type { ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwoPluginOptions } from "./contentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwoPluginOptions";

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwo =
  {
    type: string;
    required?: boolean;
    unique?: boolean;
    default?: unknown;
    min?: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwoMin;
    max?: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwoMax;
    minLength?: number;
    maxLength?: number;
    enum?: string[];
    regex?: string;
    private?: boolean;
    configurable?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwoPluginOptions;
  };
