/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfPluginOptions } from "./contentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfPluginOptions";

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOf =
  {
    type: "media";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfPluginOptions;
    multiple: boolean;
    required?: boolean;
    allowedTypes?: string[];
  };
