/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetComponentsByUid200DataSchemaAttributes } from "./contentTypeBuilderGetComponentsByUid200DataSchemaAttributes";
import type { ContentTypeBuilderGetComponentsByUid200DataSchemaPluginOptions } from "./contentTypeBuilderGetComponentsByUid200DataSchemaPluginOptions";

export type ContentTypeBuilderGetComponentsByUid200DataSchema = {
  displayName: string;
  description: string;
  icon?: string;
  connection?: string;
  collectionName?: string;
  attributes: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributes;
  pluginOptions?: ContentTypeBuilderGetComponentsByUid200DataSchemaPluginOptions;
};
