/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnezeroPluginOptions } from "./contentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnezeroPluginOptions";

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnezero =
  {
    type: "uid";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnezeroPluginOptions;
    targetField?: string;
  };
