/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfSixPluginOptions } from "./contentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfSixPluginOptions";

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfSix =
  {
    type: "component";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfSixPluginOptions;
    component: string;
    repeatable: boolean;
    required?: boolean;
    min?: number;
    max?: number;
  };
