/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfPluginOptions } from "./contentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfPluginOptions";

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOf = {
  type: "media";
  configurable?: false;
  private?: boolean;
  pluginOptions?: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfPluginOptions;
  multiple: boolean;
  required?: boolean;
  allowedTypes?: string[];
};
