/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UploadPost200AnyOfEightItemProviderMetadataAnyOf } from "./uploadPost200AnyOfEightItemProviderMetadataAnyOf";

export type UploadPost200AnyOfEightItemProviderMetadata =
  UploadPost200AnyOfEightItemProviderMetadataAnyOf | null;
