/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UploadGetFilesByIdPopulateAnyOf } from "./uploadGetFilesByIdPopulateAnyOf";

export type UploadGetFilesByIdParams = {
  /**
   * Select specific fields to return in the response
   */
  fields?: string | string[];
  /**
   * Specify which relations to populate in the response
   */
  populate?: "*" | string | string[] | UploadGetFilesByIdPopulateAnyOf;
};
