/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UploadPost200AnyOf } from "./uploadPost200AnyOf";
import type { UploadPost200AnyOfEightItem } from "./uploadPost200AnyOfEightItem";

export type UploadPost200 = UploadPost200AnyOf | UploadPost200AnyOfEightItem[];
