/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UsersPermissionsPostAuthLocalRegister200AnyOf } from "./usersPermissionsPostAuthLocalRegister200AnyOf";
import type { UsersPermissionsPostAuthLocalRegister200AnyOfSix } from "./usersPermissionsPostAuthLocalRegister200AnyOfSix";

export type UsersPermissionsPostAuthLocalRegister200 =
  | UsersPermissionsPostAuthLocalRegister200AnyOf
  | UsersPermissionsPostAuthLocalRegister200AnyOfSix;
