/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UsersPermissionsGetRoles200RolesItemDescription } from "./usersPermissionsGetRoles200RolesItemDescription";
import type { UsersPermissionsGetRoles200RolesItemPermissions } from "./usersPermissionsGetRoles200RolesItemPermissions";

export type UsersPermissionsGetRoles200RolesItem = {
  id: number;
  documentId: string;
  name: string;
  description: UsersPermissionsGetRoles200RolesItemDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  nb_users?: number;
  permissions?: UsersPermissionsGetRoles200RolesItemPermissions;
  users?: unknown[];
};
