/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UsersPermissionsPostAuthLocal200UserRole } from "./usersPermissionsPostAuthLocal200UserRole";

export type UsersPermissionsPostAuthLocal200User = {
  id: number;
  documentId: string;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  role?: UsersPermissionsPostAuthLocal200UserRole;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};
