/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UsersPermissionsGetUsers200ItemRole } from "./usersPermissionsGetUsers200ItemRole";

export type UsersPermissionsGetUsers200Item = {
  id: number;
  documentId: string;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  role?: UsersPermissionsGetUsers200ItemRole;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};
