/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UsersPermissionsGetAuthByProviderCallback200UserRoleAnyOf } from "./usersPermissionsGetAuthByProviderCallback200UserRoleAnyOf";

export type UsersPermissionsGetAuthByProviderCallback200UserRole =
  | number
  | UsersPermissionsGetAuthByProviderCallback200UserRoleAnyOf;
