/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UsersPermissionsPostAuthChangePassword200UserRoleAnyOf } from "./usersPermissionsPostAuthChangePassword200UserRoleAnyOf";

export type UsersPermissionsPostAuthChangePassword200UserRole =
  | number
  | UsersPermissionsPostAuthChangePassword200UserRoleAnyOf;
