/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UsersPermissionsDeleteUsersById200Role } from "./usersPermissionsDeleteUsersById200Role";

export type UsersPermissionsDeleteUsersById200 = {
  id: number;
  documentId: string;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  role?: UsersPermissionsDeleteUsersById200Role;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};
