/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UsersPermissionsPostAuthLocalRegister200AnyOfSixUser } from "./usersPermissionsPostAuthLocalRegister200AnyOfSixUser";

export type UsersPermissionsPostAuthLocalRegister200AnyOfSix = {
  user: UsersPermissionsPostAuthLocalRegister200AnyOfSixUser;
};
