/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UsersPermissionsGetRolesById200RoleDescription } from "./usersPermissionsGetRolesById200RoleDescription";
import type { UsersPermissionsGetRolesById200RolePermissions } from "./usersPermissionsGetRolesById200RolePermissions";

export type UsersPermissionsGetRolesById200Role = {
  id: number;
  documentId: string;
  name: string;
  description: UsersPermissionsGetRolesById200RoleDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  nb_users?: number;
  permissions?: UsersPermissionsGetRolesById200RolePermissions;
  users?: unknown[];
};
