/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UsersPermissionsPostAuthResetPassword200UserRoleAnyOfDescription } from "./usersPermissionsPostAuthResetPassword200UserRoleAnyOfDescription";

export type UsersPermissionsPostAuthResetPassword200UserRoleAnyOf = {
  id: number;
  name: string;
  description: UsersPermissionsPostAuthResetPassword200UserRoleAnyOfDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
};
