/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UsersPermissionsPostUsers200RoleAnyOf } from "./usersPermissionsPostUsers200RoleAnyOf";

export type UsersPermissionsPostUsers200Role =
  | number
  | UsersPermissionsPostUsers200RoleAnyOf;
