/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UsersPermissionsGetUsersMe200RoleAnyOfDescription } from "./usersPermissionsGetUsersMe200RoleAnyOfDescription";

export type UsersPermissionsGetUsersMe200RoleAnyOf = {
  id: number;
  name: string;
  description: UsersPermissionsGetUsersMe200RoleAnyOfDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
};
