/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { UsersPermissionsGetUsersById200RoleAnyOf } from "./usersPermissionsGetUsersById200RoleAnyOf";

export type UsersPermissionsGetUsersById200Role =
  | number
  | UsersPermissionsGetUsersById200RoleAnyOf;
