/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

export const usersPermissionsPostAuthLocalBody = zod.object({
  identifier: zod.string(),
  password: zod.string(),
});

export const usersPermissionsPostAuthLocalResponse = zod.object({
  jwt: zod.string(),
  refreshToken: zod.string().optional(),
  user: zod.object({
    id: zod.number(),
    documentId: zod.string(),
    username: zod.string(),
    email: zod.string(),
    provider: zod.string(),
    confirmed: zod.boolean(),
    blocked: zod.boolean(),
    role: zod
      .union([
        zod.number(),
        zod.object({
          id: zod.number(),
          name: zod.string(),
          description: zod.union([zod.string(), zod.null()]),
          type: zod.string(),
          createdAt: zod.string(),
          updatedAt: zod.string(),
        }),
      ])
      .optional(),
    createdAt: zod.string(),
    updatedAt: zod.string(),
    publishedAt: zod.string(),
  }),
});

export const usersPermissionsPostAuthLocalRegisterBodyEmailRegExp = new RegExp(
  "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
);

export const usersPermissionsPostAuthLocalRegisterBody = zod.object({
  username: zod.string(),
  email: zod
    .email()
    .regex(usersPermissionsPostAuthLocalRegisterBodyEmailRegExp),
  password: zod.string(),
});

export const usersPermissionsPostAuthLocalRegisterResponse = zod.union([
  zod.object({
    jwt: zod.string(),
    refreshToken: zod.string().optional(),
    user: zod.object({
      id: zod.number(),
      documentId: zod.string(),
      username: zod.string(),
      email: zod.string(),
      provider: zod.string(),
      confirmed: zod.boolean(),
      blocked: zod.boolean(),
      role: zod
        .union([
          zod.number(),
          zod.object({
            id: zod.number(),
            name: zod.string(),
            description: zod.union([zod.string(), zod.null()]),
            type: zod.string(),
            createdAt: zod.string(),
            updatedAt: zod.string(),
          }),
        ])
        .optional(),
      createdAt: zod.string(),
      updatedAt: zod.string(),
      publishedAt: zod.string(),
    }),
  }),
  zod.object({
    user: zod.object({
      id: zod.number(),
      documentId: zod.string(),
      username: zod.string(),
      email: zod.string(),
      provider: zod.string(),
      confirmed: zod.boolean(),
      blocked: zod.boolean(),
      role: zod
        .union([
          zod.number(),
          zod.object({
            id: zod.number(),
            name: zod.string(),
            description: zod.union([zod.string(), zod.null()]),
            type: zod.string(),
            createdAt: zod.string(),
            updatedAt: zod.string(),
          }),
        ])
        .optional(),
      createdAt: zod.string(),
      updatedAt: zod.string(),
      publishedAt: zod.string(),
    }),
  }),
]);

export const usersPermissionsGetAuthByProviderCallbackParams = zod.object({
  provider: zod.string(),
});

export const usersPermissionsGetAuthByProviderCallbackResponse = zod.object({
  jwt: zod.string(),
  refreshToken: zod.string().optional(),
  user: zod.object({
    id: zod.number(),
    documentId: zod.string(),
    username: zod.string(),
    email: zod.string(),
    provider: zod.string(),
    confirmed: zod.boolean(),
    blocked: zod.boolean(),
    role: zod
      .union([
        zod.number(),
        zod.object({
          id: zod.number(),
          name: zod.string(),
          description: zod.union([zod.string(), zod.null()]),
          type: zod.string(),
          createdAt: zod.string(),
          updatedAt: zod.string(),
        }),
      ])
      .optional(),
    createdAt: zod.string(),
    updatedAt: zod.string(),
    publishedAt: zod.string(),
  }),
});

export const usersPermissionsPostAuthForgotPasswordBodyEmailRegExp = new RegExp(
  "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
);

export const usersPermissionsPostAuthForgotPasswordBody = zod.object({
  email: zod
    .email()
    .regex(usersPermissionsPostAuthForgotPasswordBodyEmailRegExp),
});

export const usersPermissionsPostAuthForgotPasswordResponse = zod.object({
  ok: zod.boolean(),
});

export const usersPermissionsPostAuthResetPasswordBody = zod.object({
  code: zod.string(),
  password: zod.string(),
  passwordConfirmation: zod.string(),
});

export const usersPermissionsPostAuthResetPasswordResponse = zod.object({
  jwt: zod.string(),
  refreshToken: zod.string().optional(),
  user: zod.object({
    id: zod.number(),
    documentId: zod.string(),
    username: zod.string(),
    email: zod.string(),
    provider: zod.string(),
    confirmed: zod.boolean(),
    blocked: zod.boolean(),
    role: zod
      .union([
        zod.number(),
        zod.object({
          id: zod.number(),
          name: zod.string(),
          description: zod.union([zod.string(), zod.null()]),
          type: zod.string(),
          createdAt: zod.string(),
          updatedAt: zod.string(),
        }),
      ])
      .optional(),
    createdAt: zod.string(),
    updatedAt: zod.string(),
    publishedAt: zod.string(),
  }),
});

export const usersPermissionsPostAuthSendEmailConfirmationBodyEmailRegExp =
  new RegExp(
    "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
  );

export const usersPermissionsPostAuthSendEmailConfirmationBody = zod.object({
  email: zod
    .email()
    .regex(usersPermissionsPostAuthSendEmailConfirmationBodyEmailRegExp),
});

export const usersPermissionsPostAuthSendEmailConfirmationResponse = zod.object(
  {
    email: zod.string(),
    sent: zod.boolean(),
  },
);

export const usersPermissionsPostAuthChangePasswordBody = zod.object({
  currentPassword: zod.string(),
  password: zod.string(),
  passwordConfirmation: zod.string(),
});

export const usersPermissionsPostAuthChangePasswordResponse = zod.object({
  jwt: zod.string(),
  refreshToken: zod.string().optional(),
  user: zod.object({
    id: zod.number(),
    documentId: zod.string(),
    username: zod.string(),
    email: zod.string(),
    provider: zod.string(),
    confirmed: zod.boolean(),
    blocked: zod.boolean(),
    role: zod
      .union([
        zod.number(),
        zod.object({
          id: zod.number(),
          name: zod.string(),
          description: zod.union([zod.string(), zod.null()]),
          type: zod.string(),
          createdAt: zod.string(),
          updatedAt: zod.string(),
        }),
      ])
      .optional(),
    createdAt: zod.string(),
    updatedAt: zod.string(),
    publishedAt: zod.string(),
  }),
});

export const usersPermissionsGetUsersCountQueryParams = zod.object({
  filters: zod.record(zod.string(), zod.unknown()).optional(),
});

export const usersPermissionsGetUsersCountResponse = zod.number();

export const usersPermissionsGetUsersQueryPaginationPageMax = 9007199254740991;

export const usersPermissionsGetUsersQueryPaginationPageSizeMax = 9007199254740991;

export const usersPermissionsGetUsersQueryPaginationStartMin = 0;
export const usersPermissionsGetUsersQueryPaginationStartMax = 9007199254740991;

export const usersPermissionsGetUsersQueryPaginationLimitMax = 9007199254740991;

export const usersPermissionsGetUsersQueryParams = zod.object({
  fields: zod.union([zod.string(), zod.array(zod.string())]).optional(),
  populate: zod
    .union([
      zod.literal("*"),
      zod.string(),
      zod.array(zod.string()),
      zod.record(zod.string(), zod.unknown()),
    ])
    .optional(),
  sort: zod
    .union([
      zod.string(),
      zod.array(zod.string()),
      zod.record(zod.string(), zod.enum(["asc", "desc"])),
      zod.array(zod.record(zod.string(), zod.enum(["asc", "desc"]))),
    ])
    .optional(),
  pagination: zod
    .object({
      withCount: zod
        .boolean()
        .optional()
        .describe("Include total count in response"),
    })
    .and(
      zod.union([
        zod
          .object({
            page: zod
              .number()
              .max(usersPermissionsGetUsersQueryPaginationPageMax)
              .describe("Page number (1-based)"),
            pageSize: zod
              .number()
              .max(usersPermissionsGetUsersQueryPaginationPageSizeMax)
              .describe("Number of entries per page"),
          })
          .describe("Page-based pagination"),
        zod
          .object({
            start: zod
              .number()
              .min(usersPermissionsGetUsersQueryPaginationStartMin)
              .max(usersPermissionsGetUsersQueryPaginationStartMax)
              .describe("Number of entries to skip"),
            limit: zod
              .number()
              .max(usersPermissionsGetUsersQueryPaginationLimitMax)
              .describe("Maximum number of entries to return"),
          })
          .describe("Offset-based pagination"),
      ]),
    )
    .optional(),
  filters: zod.record(zod.string(), zod.unknown()).optional(),
});

export const usersPermissionsGetUsersResponseItem = zod.object({
  id: zod.number(),
  documentId: zod.string(),
  username: zod.string(),
  email: zod.string(),
  provider: zod.string(),
  confirmed: zod.boolean(),
  blocked: zod.boolean(),
  role: zod
    .union([
      zod.number(),
      zod.object({
        id: zod.number(),
        name: zod.string(),
        description: zod.union([zod.string(), zod.null()]),
        type: zod.string(),
        createdAt: zod.string(),
        updatedAt: zod.string(),
      }),
    ])
    .optional(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
  publishedAt: zod.string(),
});
export const usersPermissionsGetUsersResponse = zod.array(
  usersPermissionsGetUsersResponseItem,
);

export const usersPermissionsPostUsersBodyEmailRegExp = new RegExp(
  "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
);

export const usersPermissionsPostUsersBody = zod.object({
  username: zod.string(),
  email: zod.email().regex(usersPermissionsPostUsersBodyEmailRegExp),
  password: zod.string(),
  role: zod.number().optional(),
});

export const usersPermissionsPostUsersResponse = zod.object({
  id: zod.number(),
  documentId: zod.string(),
  username: zod.string(),
  email: zod.string(),
  provider: zod.string(),
  confirmed: zod.boolean(),
  blocked: zod.boolean(),
  role: zod
    .union([
      zod.number(),
      zod.object({
        id: zod.number(),
        name: zod.string(),
        description: zod.union([zod.string(), zod.null()]),
        type: zod.string(),
        createdAt: zod.string(),
        updatedAt: zod.string(),
      }),
    ])
    .optional(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
  publishedAt: zod.string(),
});

export const usersPermissionsGetUsersMeQueryParams = zod.object({
  fields: zod.union([zod.string(), zod.array(zod.string())]).optional(),
  populate: zod
    .union([
      zod.literal("*"),
      zod.string(),
      zod.array(zod.string()),
      zod.record(zod.string(), zod.unknown()),
    ])
    .optional(),
});

export const usersPermissionsGetUsersMeResponse = zod.object({
  id: zod.number(),
  documentId: zod.string(),
  username: zod.string(),
  email: zod.string(),
  provider: zod.string(),
  confirmed: zod.boolean(),
  blocked: zod.boolean(),
  role: zod
    .union([
      zod.number(),
      zod.object({
        id: zod.number(),
        name: zod.string(),
        description: zod.union([zod.string(), zod.null()]),
        type: zod.string(),
        createdAt: zod.string(),
        updatedAt: zod.string(),
      }),
    ])
    .optional(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
  publishedAt: zod.string(),
});

export const usersPermissionsGetUsersByIdParams = zod.object({
  id: zod.string(),
});

export const usersPermissionsGetUsersByIdQueryParams = zod.object({
  fields: zod.union([zod.string(), zod.array(zod.string())]).optional(),
  populate: zod
    .union([
      zod.literal("*"),
      zod.string(),
      zod.array(zod.string()),
      zod.record(zod.string(), zod.unknown()),
    ])
    .optional(),
});

export const usersPermissionsGetUsersByIdResponse = zod.object({
  id: zod.number(),
  documentId: zod.string(),
  username: zod.string(),
  email: zod.string(),
  provider: zod.string(),
  confirmed: zod.boolean(),
  blocked: zod.boolean(),
  role: zod
    .union([
      zod.number(),
      zod.object({
        id: zod.number(),
        name: zod.string(),
        description: zod.union([zod.string(), zod.null()]),
        type: zod.string(),
        createdAt: zod.string(),
        updatedAt: zod.string(),
      }),
    ])
    .optional(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
  publishedAt: zod.string(),
});

export const usersPermissionsPutUsersByIdParams = zod.object({
  id: zod.string(),
});

export const usersPermissionsPutUsersByIdBodyEmailRegExp = new RegExp(
  "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
);

export const usersPermissionsPutUsersByIdBody = zod.object({
  username: zod.string().optional(),
  email: zod
    .email()
    .regex(usersPermissionsPutUsersByIdBodyEmailRegExp)
    .optional(),
  password: zod.string().optional(),
  role: zod.number().optional(),
});

export const usersPermissionsPutUsersByIdResponse = zod.object({
  id: zod.number(),
  documentId: zod.string(),
  username: zod.string(),
  email: zod.string(),
  provider: zod.string(),
  confirmed: zod.boolean(),
  blocked: zod.boolean(),
  role: zod
    .union([
      zod.number(),
      zod.object({
        id: zod.number(),
        name: zod.string(),
        description: zod.union([zod.string(), zod.null()]),
        type: zod.string(),
        createdAt: zod.string(),
        updatedAt: zod.string(),
      }),
    ])
    .optional(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
  publishedAt: zod.string(),
});

export const usersPermissionsDeleteUsersByIdParams = zod.object({
  id: zod.string(),
});

export const usersPermissionsDeleteUsersByIdResponse = zod.object({
  id: zod.number(),
  documentId: zod.string(),
  username: zod.string(),
  email: zod.string(),
  provider: zod.string(),
  confirmed: zod.boolean(),
  blocked: zod.boolean(),
  role: zod
    .union([
      zod.number(),
      zod.object({
        id: zod.number(),
        name: zod.string(),
        description: zod.union([zod.string(), zod.null()]),
        type: zod.string(),
        createdAt: zod.string(),
        updatedAt: zod.string(),
      }),
    ])
    .optional(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
  publishedAt: zod.string(),
});

export const usersPermissionsGetRolesByIdParams = zod.object({
  id: zod.string(),
});

export const usersPermissionsGetRolesByIdResponse = zod.object({
  role: zod.object({
    id: zod.number(),
    documentId: zod.string(),
    name: zod.string(),
    description: zod.union([zod.string(), zod.null()]),
    type: zod.string(),
    createdAt: zod.string(),
    updatedAt: zod.string(),
    publishedAt: zod.string(),
    nb_users: zod.number().optional(),
    permissions: zod
      .record(
        zod.string(),
        zod.object({
          controllers: zod.record(
            zod.string(),
            zod.record(
              zod.string(),
              zod.object({
                enabled: zod.boolean(),
                policy: zod.string(),
              }),
            ),
          ),
        }),
      )
      .optional(),
    users: zod.array(zod.unknown()).optional(),
  }),
});

export const usersPermissionsGetRolesResponse = zod.object({
  roles: zod.array(
    zod.object({
      id: zod.number(),
      documentId: zod.string(),
      name: zod.string(),
      description: zod.union([zod.string(), zod.null()]),
      type: zod.string(),
      createdAt: zod.string(),
      updatedAt: zod.string(),
      publishedAt: zod.string(),
      nb_users: zod.number().optional(),
      permissions: zod
        .record(
          zod.string(),
          zod.object({
            controllers: zod.record(
              zod.string(),
              zod.record(
                zod.string(),
                zod.object({
                  enabled: zod.boolean(),
                  policy: zod.string(),
                }),
              ),
            ),
          }),
        )
        .optional(),
      users: zod.array(zod.unknown()).optional(),
    }),
  ),
});

export const usersPermissionsPostRolesBody = zod.object({
  name: zod.string(),
  description: zod.string().optional(),
  type: zod.string(),
  permissions: zod.record(zod.string(), zod.unknown()).optional(),
});

export const usersPermissionsPostRolesResponse = zod.object({
  ok: zod.boolean(),
});

export const usersPermissionsPutRolesByRoleParams = zod.object({
  role: zod.string(),
});

export const usersPermissionsPutRolesByRoleBody = zod.object({
  name: zod.string().optional(),
  description: zod.string().optional(),
  type: zod.string().optional(),
  permissions: zod.record(zod.string(), zod.unknown()).optional(),
});

export const usersPermissionsPutRolesByRoleResponse = zod.object({
  ok: zod.boolean(),
});

export const usersPermissionsDeleteRolesByRoleParams = zod.object({
  role: zod.string(),
});

export const usersPermissionsDeleteRolesByRoleResponse = zod.object({
  ok: zod.boolean(),
});

export const usersPermissionsGetPermissionsResponse = zod.object({
  permissions: zod.record(
    zod.string(),
    zod.object({
      controllers: zod.record(
        zod.string(),
        zod.record(
          zod.string(),
          zod.object({
            enabled: zod.boolean(),
            policy: zod.string(),
          }),
        ),
      ),
    }),
  ),
});
