/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

export const i18nGetLocalesResponseIdMax = 9007199254740991;

export const i18nGetLocalesResponseDocumentIdRegExp = new RegExp(
  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
);
export const i18nGetLocalesResponseCodeMin = 2;
export const i18nGetLocalesResponseCodeMax = 2;

export const i18nGetLocalesResponseItem = zod.object({
  id: zod.number().max(i18nGetLocalesResponseIdMax),
  documentId: zod.uuid().regex(i18nGetLocalesResponseDocumentIdRegExp),
  name: zod.string(),
  code: zod
    .string()
    .min(i18nGetLocalesResponseCodeMin)
    .max(i18nGetLocalesResponseCodeMax),
  createdAt: zod.string(),
  updatedAt: zod.string(),
  publishedAt: zod.union([zod.string(), zod.null()]),
  isDefault: zod.boolean(),
});
export const i18nGetLocalesResponse = zod.array(i18nGetLocalesResponseItem);
