/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type {
  UploadDeleteFilesById200,
  UploadGetFiles200Item,
  UploadGetFilesById200,
  UploadGetFilesByIdParams,
  UploadGetFilesParams,
  UploadPost200,
  UploadPostParams,
} from "../learningStrapiV5.schemas";

import { strapiClient } from "../../../lib/strapi-client";

export const getUpload = () => {
  const uploadPost = (params?: UploadPostParams) => {
    return strapiClient<UploadPost200>({ url: `/`, method: "POST", params });
  };
  const uploadGetFiles = (params?: UploadGetFilesParams) => {
    return strapiClient<UploadGetFiles200Item[]>({
      url: `/files`,
      method: "GET",
      params,
    });
  };
  const uploadGetFilesById = (
    id: number,
    params?: UploadGetFilesByIdParams,
  ) => {
    return strapiClient<UploadGetFilesById200>({
      url: `/files/${id}`,
      method: "GET",
      params,
    });
  };
  const uploadDeleteFilesById = (id: number) => {
    return strapiClient<UploadDeleteFilesById200>({
      url: `/files/${id}`,
      method: "DELETE",
    });
  };
  return {
    uploadPost,
    uploadGetFiles,
    uploadGetFilesById,
    uploadDeleteFilesById,
  };
};
export type UploadPostResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUpload>["uploadPost"]>>
>;
export type UploadGetFilesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUpload>["uploadGetFiles"]>>
>;
export type UploadGetFilesByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUpload>["uploadGetFilesById"]>>
>;
export type UploadDeleteFilesByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUpload>["uploadDeleteFilesById"]>>
>;
