/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

export const contentTypeBuilderGetContentTypesQueryParams = zod.object({
  kind: zod.enum(["collectionType", "singleType"]),
});

export const contentTypeBuilderGetContentTypesResponseDataItemUidRegExp =
  new RegExp("^((strapi|admin)::[\\w-]+|(api|plugin)::[\\w-]+\\.[\\w-]+)$");
export const contentTypeBuilderGetContentTypesResponseDataItemSchemaAttributesTargetRegExp =
  new RegExp("^((strapi|admin)::[\\w-]+|(api|plugin)::[\\w-]+\\.[\\w-]+)$");
export const contentTypeBuilderGetContentTypesResponseDataItemSchemaAttributesComponentsItemRegExp =
  new RegExp("^[\\w-]+\\.[\\w-]+$");

export const contentTypeBuilderGetContentTypesResponse = zod.object({
  data: zod.array(
    zod.object({
      uid: zod
        .string()
        .regex(contentTypeBuilderGetContentTypesResponseDataItemUidRegExp),
      plugin: zod.string().optional(),
      apiID: zod.string(),
      schema: zod.object({
        displayName: zod.string(),
        singularName: zod.string(),
        pluralName: zod.string(),
        description: zod.string(),
        draftAndPublish: zod.boolean(),
        kind: zod.enum(["collectionType", "singleType"]),
        collectionName: zod.string().optional(),
        attributes: zod.record(
          zod.string(),
          zod.union([
            zod.object({
              type: zod.literal("media"),
              configurable: zod.boolean().optional(),
              private: zod.boolean().optional(),
              pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
              multiple: zod.boolean(),
              required: zod.boolean().optional(),
              allowedTypes: zod.array(zod.string()).optional(),
            }),
            zod.object({
              type: zod.literal("relation"),
              configurable: zod.boolean().optional(),
              private: zod.boolean().optional(),
              pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
              relation: zod.string(),
              target: zod
                .string()
                .regex(
                  contentTypeBuilderGetContentTypesResponseDataItemSchemaAttributesTargetRegExp,
                ),
              targetAttribute: zod.union([zod.string(), zod.null()]),
              autoPopulate: zod.boolean().optional(),
              mappedBy: zod.string().optional(),
              inversedBy: zod.string().optional(),
            }),
            zod.object({
              type: zod.literal("component"),
              configurable: zod.boolean().optional(),
              private: zod.boolean().optional(),
              pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
              component: zod.string(),
              repeatable: zod.boolean(),
              required: zod.boolean().optional(),
              min: zod.number().optional(),
              max: zod.number().optional(),
            }),
            zod.object({
              type: zod.literal("dynamiczone"),
              configurable: zod.boolean().optional(),
              private: zod.boolean().optional(),
              pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
              components: zod.array(
                zod
                  .string()
                  .regex(
                    contentTypeBuilderGetContentTypesResponseDataItemSchemaAttributesComponentsItemRegExp,
                  ),
              ),
              required: zod.boolean().optional(),
              min: zod.number().optional(),
              max: zod.number().optional(),
            }),
            zod.object({
              type: zod.literal("uid"),
              configurable: zod.boolean().optional(),
              private: zod.boolean().optional(),
              pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
              targetField: zod.string().optional(),
            }),
            zod.object({
              type: zod.string(),
              required: zod.boolean().optional(),
              unique: zod.boolean().optional(),
              default: zod.unknown().optional(),
              min: zod.union([zod.number(), zod.string()]).optional(),
              max: zod.union([zod.number(), zod.string()]).optional(),
              minLength: zod.number().optional(),
              maxLength: zod.number().optional(),
              enum: zod.array(zod.string()).optional(),
              regex: zod.string().optional(),
              private: zod.boolean().optional(),
              configurable: zod.boolean().optional(),
              pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
            }),
          ]),
        ),
        visible: zod.boolean(),
        restrictRelationsTo: zod.union([zod.array(zod.string()), zod.null()]),
        pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
        options: zod.record(zod.string(), zod.unknown()).optional(),
        reviewWorkflows: zod.boolean().optional(),
        populateCreatorFields: zod.boolean().optional(),
        comment: zod.string().optional(),
        version: zod.string().optional(),
      }),
    }),
  ),
});

export const contentTypeBuilderGetContentTypesByUidPathUidRegExp = new RegExp(
  "^((strapi|admin)::[\\w-]+|(api|plugin)::[\\w-]+\\.[\\w-]+)$",
);

export const contentTypeBuilderGetContentTypesByUidParams = zod.object({
  uid: zod.string().regex(contentTypeBuilderGetContentTypesByUidPathUidRegExp),
});

export const contentTypeBuilderGetContentTypesByUidResponseDataUidRegExp =
  new RegExp("^((strapi|admin)::[\\w-]+|(api|plugin)::[\\w-]+\\.[\\w-]+)$");
export const contentTypeBuilderGetContentTypesByUidResponseDataSchemaAttributesTargetRegExp =
  new RegExp("^((strapi|admin)::[\\w-]+|(api|plugin)::[\\w-]+\\.[\\w-]+)$");
export const contentTypeBuilderGetContentTypesByUidResponseDataSchemaAttributesComponentsItemRegExp =
  new RegExp("^[\\w-]+\\.[\\w-]+$");

export const contentTypeBuilderGetContentTypesByUidResponse = zod.object({
  data: zod.object({
    uid: zod
      .string()
      .regex(contentTypeBuilderGetContentTypesByUidResponseDataUidRegExp),
    plugin: zod.string().optional(),
    apiID: zod.string(),
    schema: zod.object({
      displayName: zod.string(),
      singularName: zod.string(),
      pluralName: zod.string(),
      description: zod.string(),
      draftAndPublish: zod.boolean(),
      kind: zod.enum(["collectionType", "singleType"]),
      collectionName: zod.string().optional(),
      attributes: zod.record(
        zod.string(),
        zod.union([
          zod.object({
            type: zod.literal("media"),
            configurable: zod.boolean().optional(),
            private: zod.boolean().optional(),
            pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
            multiple: zod.boolean(),
            required: zod.boolean().optional(),
            allowedTypes: zod.array(zod.string()).optional(),
          }),
          zod.object({
            type: zod.literal("relation"),
            configurable: zod.boolean().optional(),
            private: zod.boolean().optional(),
            pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
            relation: zod.string(),
            target: zod
              .string()
              .regex(
                contentTypeBuilderGetContentTypesByUidResponseDataSchemaAttributesTargetRegExp,
              ),
            targetAttribute: zod.union([zod.string(), zod.null()]),
            autoPopulate: zod.boolean().optional(),
            mappedBy: zod.string().optional(),
            inversedBy: zod.string().optional(),
          }),
          zod.object({
            type: zod.literal("component"),
            configurable: zod.boolean().optional(),
            private: zod.boolean().optional(),
            pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
            component: zod.string(),
            repeatable: zod.boolean(),
            required: zod.boolean().optional(),
            min: zod.number().optional(),
            max: zod.number().optional(),
          }),
          zod.object({
            type: zod.literal("dynamiczone"),
            configurable: zod.boolean().optional(),
            private: zod.boolean().optional(),
            pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
            components: zod.array(
              zod
                .string()
                .regex(
                  contentTypeBuilderGetContentTypesByUidResponseDataSchemaAttributesComponentsItemRegExp,
                ),
            ),
            required: zod.boolean().optional(),
            min: zod.number().optional(),
            max: zod.number().optional(),
          }),
          zod.object({
            type: zod.literal("uid"),
            configurable: zod.boolean().optional(),
            private: zod.boolean().optional(),
            pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
            targetField: zod.string().optional(),
          }),
          zod.object({
            type: zod.string(),
            required: zod.boolean().optional(),
            unique: zod.boolean().optional(),
            default: zod.unknown().optional(),
            min: zod.union([zod.number(), zod.string()]).optional(),
            max: zod.union([zod.number(), zod.string()]).optional(),
            minLength: zod.number().optional(),
            maxLength: zod.number().optional(),
            enum: zod.array(zod.string()).optional(),
            regex: zod.string().optional(),
            private: zod.boolean().optional(),
            configurable: zod.boolean().optional(),
            pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
          }),
        ]),
      ),
      visible: zod.boolean(),
      restrictRelationsTo: zod.union([zod.array(zod.string()), zod.null()]),
      pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
      options: zod.record(zod.string(), zod.unknown()).optional(),
      reviewWorkflows: zod.boolean().optional(),
      populateCreatorFields: zod.boolean().optional(),
      comment: zod.string().optional(),
      version: zod.string().optional(),
    }),
  }),
});

export const contentTypeBuilderGetComponentsResponseDataItemUidRegExp =
  new RegExp("^[\\w-]+\\.[\\w-]+$");
export const contentTypeBuilderGetComponentsResponseDataItemSchemaAttributesTargetRegExp =
  new RegExp("^((strapi|admin)::[\\w-]+|(api|plugin)::[\\w-]+\\.[\\w-]+)$");
export const contentTypeBuilderGetComponentsResponseDataItemSchemaAttributesComponentsItemRegExp =
  new RegExp("^[\\w-]+\\.[\\w-]+$");

export const contentTypeBuilderGetComponentsResponse = zod.object({
  data: zod.array(
    zod.object({
      uid: zod
        .string()
        .regex(contentTypeBuilderGetComponentsResponseDataItemUidRegExp),
      category: zod.string(),
      apiId: zod.string(),
      schema: zod.object({
        displayName: zod.string(),
        description: zod.string(),
        icon: zod.string().optional(),
        connection: zod.string().optional(),
        collectionName: zod.string().optional(),
        attributes: zod.record(
          zod.string(),
          zod.union([
            zod.object({
              type: zod.literal("media"),
              configurable: zod.boolean().optional(),
              private: zod.boolean().optional(),
              pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
              multiple: zod.boolean(),
              required: zod.boolean().optional(),
              allowedTypes: zod.array(zod.string()).optional(),
            }),
            zod.object({
              type: zod.literal("relation"),
              configurable: zod.boolean().optional(),
              private: zod.boolean().optional(),
              pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
              relation: zod.string(),
              target: zod
                .string()
                .regex(
                  contentTypeBuilderGetComponentsResponseDataItemSchemaAttributesTargetRegExp,
                ),
              targetAttribute: zod.union([zod.string(), zod.null()]),
              autoPopulate: zod.boolean().optional(),
              mappedBy: zod.string().optional(),
              inversedBy: zod.string().optional(),
            }),
            zod.object({
              type: zod.literal("component"),
              configurable: zod.boolean().optional(),
              private: zod.boolean().optional(),
              pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
              component: zod.string(),
              repeatable: zod.boolean(),
              required: zod.boolean().optional(),
              min: zod.number().optional(),
              max: zod.number().optional(),
            }),
            zod.object({
              type: zod.literal("dynamiczone"),
              configurable: zod.boolean().optional(),
              private: zod.boolean().optional(),
              pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
              components: zod.array(
                zod
                  .string()
                  .regex(
                    contentTypeBuilderGetComponentsResponseDataItemSchemaAttributesComponentsItemRegExp,
                  ),
              ),
              required: zod.boolean().optional(),
              min: zod.number().optional(),
              max: zod.number().optional(),
            }),
            zod.object({
              type: zod.literal("uid"),
              configurable: zod.boolean().optional(),
              private: zod.boolean().optional(),
              pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
              targetField: zod.string().optional(),
            }),
            zod.object({
              type: zod.string(),
              required: zod.boolean().optional(),
              unique: zod.boolean().optional(),
              default: zod.unknown().optional(),
              min: zod.union([zod.number(), zod.string()]).optional(),
              max: zod.union([zod.number(), zod.string()]).optional(),
              minLength: zod.number().optional(),
              maxLength: zod.number().optional(),
              enum: zod.array(zod.string()).optional(),
              regex: zod.string().optional(),
              private: zod.boolean().optional(),
              configurable: zod.boolean().optional(),
              pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
            }),
          ]),
        ),
        pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
      }),
    }),
  ),
});

export const contentTypeBuilderGetComponentsByUidPathUidRegExp = new RegExp(
  "^[\\w-]+\\.[\\w-]+$",
);

export const contentTypeBuilderGetComponentsByUidParams = zod.object({
  uid: zod.string().regex(contentTypeBuilderGetComponentsByUidPathUidRegExp),
});

export const contentTypeBuilderGetComponentsByUidResponseDataUidRegExp =
  new RegExp("^[\\w-]+\\.[\\w-]+$");
export const contentTypeBuilderGetComponentsByUidResponseDataSchemaAttributesTargetRegExp =
  new RegExp("^((strapi|admin)::[\\w-]+|(api|plugin)::[\\w-]+\\.[\\w-]+)$");
export const contentTypeBuilderGetComponentsByUidResponseDataSchemaAttributesComponentsItemRegExp =
  new RegExp("^[\\w-]+\\.[\\w-]+$");

export const contentTypeBuilderGetComponentsByUidResponse = zod.object({
  data: zod.object({
    uid: zod
      .string()
      .regex(contentTypeBuilderGetComponentsByUidResponseDataUidRegExp),
    category: zod.string(),
    apiId: zod.string(),
    schema: zod.object({
      displayName: zod.string(),
      description: zod.string(),
      icon: zod.string().optional(),
      connection: zod.string().optional(),
      collectionName: zod.string().optional(),
      attributes: zod.record(
        zod.string(),
        zod.union([
          zod.object({
            type: zod.literal("media"),
            configurable: zod.boolean().optional(),
            private: zod.boolean().optional(),
            pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
            multiple: zod.boolean(),
            required: zod.boolean().optional(),
            allowedTypes: zod.array(zod.string()).optional(),
          }),
          zod.object({
            type: zod.literal("relation"),
            configurable: zod.boolean().optional(),
            private: zod.boolean().optional(),
            pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
            relation: zod.string(),
            target: zod
              .string()
              .regex(
                contentTypeBuilderGetComponentsByUidResponseDataSchemaAttributesTargetRegExp,
              ),
            targetAttribute: zod.union([zod.string(), zod.null()]),
            autoPopulate: zod.boolean().optional(),
            mappedBy: zod.string().optional(),
            inversedBy: zod.string().optional(),
          }),
          zod.object({
            type: zod.literal("component"),
            configurable: zod.boolean().optional(),
            private: zod.boolean().optional(),
            pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
            component: zod.string(),
            repeatable: zod.boolean(),
            required: zod.boolean().optional(),
            min: zod.number().optional(),
            max: zod.number().optional(),
          }),
          zod.object({
            type: zod.literal("dynamiczone"),
            configurable: zod.boolean().optional(),
            private: zod.boolean().optional(),
            pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
            components: zod.array(
              zod
                .string()
                .regex(
                  contentTypeBuilderGetComponentsByUidResponseDataSchemaAttributesComponentsItemRegExp,
                ),
            ),
            required: zod.boolean().optional(),
            min: zod.number().optional(),
            max: zod.number().optional(),
          }),
          zod.object({
            type: zod.literal("uid"),
            configurable: zod.boolean().optional(),
            private: zod.boolean().optional(),
            pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
            targetField: zod.string().optional(),
          }),
          zod.object({
            type: zod.string(),
            required: zod.boolean().optional(),
            unique: zod.boolean().optional(),
            default: zod.unknown().optional(),
            min: zod.union([zod.number(), zod.string()]).optional(),
            max: zod.union([zod.number(), zod.string()]).optional(),
            minLength: zod.number().optional(),
            maxLength: zod.number().optional(),
            enum: zod.array(zod.string()).optional(),
            regex: zod.string().optional(),
            private: zod.boolean().optional(),
            configurable: zod.boolean().optional(),
            pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
          }),
        ]),
      ),
      pluginOptions: zod.record(zod.string(), zod.unknown()).optional(),
    }),
  }),
});
