/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

export const uploadPostQueryIdMax = 9007199254740991;

export const uploadPostQueryParams = zod.object({
  id: zod.number().max(uploadPostQueryIdMax).optional(),
});

export const uploadPostResponseIdMax = 9007199254740991;

export const uploadPostResponseDocumentIdRegExp = new RegExp(
  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
);
export const uploadPostResponseWidthMin = -9007199254740991;
export const uploadPostResponseWidthMax = 9007199254740991;

export const uploadPostResponseHeightMin = -9007199254740991;
export const uploadPostResponseHeightMax = 9007199254740991;

export const uploadPostResponseItemIdMax = 9007199254740991;

export const uploadPostResponseItemDocumentIdRegExp = new RegExp(
  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
);
export const uploadPostResponseItemWidthMin = -9007199254740991;
export const uploadPostResponseItemWidthMax = 9007199254740991;

export const uploadPostResponseItemHeightMin = -9007199254740991;
export const uploadPostResponseItemHeightMax = 9007199254740991;

export const uploadPostResponse = zod.union([
  zod.object({
    id: zod.number().max(uploadPostResponseIdMax),
    documentId: zod.uuid().regex(uploadPostResponseDocumentIdRegExp),
    name: zod.string(),
    alternativeText: zod.union([zod.string(), zod.null()]).optional(),
    caption: zod.union([zod.string(), zod.null()]).optional(),
    width: zod
      .number()
      .min(uploadPostResponseWidthMin)
      .max(uploadPostResponseWidthMax)
      .optional(),
    height: zod
      .number()
      .min(uploadPostResponseHeightMin)
      .max(uploadPostResponseHeightMax)
      .optional(),
    formats: zod.record(zod.string(), zod.unknown()).optional(),
    hash: zod.string(),
    ext: zod.string().optional(),
    mime: zod.string(),
    size: zod.number(),
    url: zod.string(),
    previewUrl: zod.union([zod.string(), zod.null()]).optional(),
    folder: zod.number().optional(),
    folderPath: zod.string(),
    provider: zod.string(),
    provider_metadata: zod
      .union([zod.record(zod.string(), zod.unknown()), zod.null()])
      .optional(),
    createdAt: zod.string(),
    updatedAt: zod.string(),
    createdBy: zod.number().optional(),
    updatedBy: zod.number().optional(),
  }),
  zod.array(
    zod.object({
      id: zod.number().max(uploadPostResponseItemIdMax),
      documentId: zod.uuid().regex(uploadPostResponseItemDocumentIdRegExp),
      name: zod.string(),
      alternativeText: zod.union([zod.string(), zod.null()]).optional(),
      caption: zod.union([zod.string(), zod.null()]).optional(),
      width: zod
        .number()
        .min(uploadPostResponseItemWidthMin)
        .max(uploadPostResponseItemWidthMax)
        .optional(),
      height: zod
        .number()
        .min(uploadPostResponseItemHeightMin)
        .max(uploadPostResponseItemHeightMax)
        .optional(),
      formats: zod.record(zod.string(), zod.unknown()).optional(),
      hash: zod.string(),
      ext: zod.string().optional(),
      mime: zod.string(),
      size: zod.number(),
      url: zod.string(),
      previewUrl: zod.union([zod.string(), zod.null()]).optional(),
      folder: zod.number().optional(),
      folderPath: zod.string(),
      provider: zod.string(),
      provider_metadata: zod
        .union([zod.record(zod.string(), zod.unknown()), zod.null()])
        .optional(),
      createdAt: zod.string(),
      updatedAt: zod.string(),
      createdBy: zod.number().optional(),
      updatedBy: zod.number().optional(),
    }),
  ),
]);

export const uploadGetFilesQueryPaginationPageMax = 9007199254740991;

export const uploadGetFilesQueryPaginationPageSizeMax = 9007199254740991;

export const uploadGetFilesQueryPaginationStartMin = 0;
export const uploadGetFilesQueryPaginationStartMax = 9007199254740991;

export const uploadGetFilesQueryPaginationLimitMax = 9007199254740991;

export const uploadGetFilesQueryParams = zod.object({
  fields: zod.union([zod.string(), zod.array(zod.string())]).optional(),
  populate: zod
    .union([
      zod.literal("*"),
      zod.string(),
      zod.array(zod.string()),
      zod.record(zod.string(), zod.unknown()),
    ])
    .optional(),
  sort: zod
    .union([
      zod.string(),
      zod.array(zod.string()),
      zod.record(zod.string(), zod.enum(["asc", "desc"])),
      zod.array(zod.record(zod.string(), zod.enum(["asc", "desc"]))),
    ])
    .optional(),
  pagination: zod
    .object({
      withCount: zod
        .boolean()
        .optional()
        .describe("Include total count in response"),
    })
    .and(
      zod.union([
        zod
          .object({
            page: zod
              .number()
              .max(uploadGetFilesQueryPaginationPageMax)
              .describe("Page number (1-based)"),
            pageSize: zod
              .number()
              .max(uploadGetFilesQueryPaginationPageSizeMax)
              .describe("Number of entries per page"),
          })
          .describe("Page-based pagination"),
        zod
          .object({
            start: zod
              .number()
              .min(uploadGetFilesQueryPaginationStartMin)
              .max(uploadGetFilesQueryPaginationStartMax)
              .describe("Number of entries to skip"),
            limit: zod
              .number()
              .max(uploadGetFilesQueryPaginationLimitMax)
              .describe("Maximum number of entries to return"),
          })
          .describe("Offset-based pagination"),
      ]),
    )
    .optional(),
  filters: zod.record(zod.string(), zod.unknown()).optional(),
});

export const uploadGetFilesResponseIdMax = 9007199254740991;

export const uploadGetFilesResponseDocumentIdRegExp = new RegExp(
  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
);
export const uploadGetFilesResponseWidthMin = -9007199254740991;
export const uploadGetFilesResponseWidthMax = 9007199254740991;

export const uploadGetFilesResponseHeightMin = -9007199254740991;
export const uploadGetFilesResponseHeightMax = 9007199254740991;

export const uploadGetFilesResponseItem = zod.object({
  id: zod.number().max(uploadGetFilesResponseIdMax),
  documentId: zod.uuid().regex(uploadGetFilesResponseDocumentIdRegExp),
  name: zod.string(),
  alternativeText: zod.union([zod.string(), zod.null()]).optional(),
  caption: zod.union([zod.string(), zod.null()]).optional(),
  width: zod
    .number()
    .min(uploadGetFilesResponseWidthMin)
    .max(uploadGetFilesResponseWidthMax)
    .optional(),
  height: zod
    .number()
    .min(uploadGetFilesResponseHeightMin)
    .max(uploadGetFilesResponseHeightMax)
    .optional(),
  formats: zod.record(zod.string(), zod.unknown()).optional(),
  hash: zod.string(),
  ext: zod.string().optional(),
  mime: zod.string(),
  size: zod.number(),
  url: zod.string(),
  previewUrl: zod.union([zod.string(), zod.null()]).optional(),
  folder: zod.number().optional(),
  folderPath: zod.string(),
  provider: zod.string(),
  provider_metadata: zod
    .union([zod.record(zod.string(), zod.unknown()), zod.null()])
    .optional(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
  createdBy: zod.number().optional(),
  updatedBy: zod.number().optional(),
});
export const uploadGetFilesResponse = zod.array(uploadGetFilesResponseItem);

export const uploadGetFilesByIdPathIdMax = 9007199254740991;

export const uploadGetFilesByIdParams = zod.object({
  id: zod.number().max(uploadGetFilesByIdPathIdMax),
});

export const uploadGetFilesByIdQueryParams = zod.object({
  fields: zod.union([zod.string(), zod.array(zod.string())]).optional(),
  populate: zod
    .union([
      zod.literal("*"),
      zod.string(),
      zod.array(zod.string()),
      zod.record(zod.string(), zod.unknown()),
    ])
    .optional(),
});

export const uploadGetFilesByIdResponseIdMax = 9007199254740991;

export const uploadGetFilesByIdResponseDocumentIdRegExp = new RegExp(
  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
);
export const uploadGetFilesByIdResponseWidthMin = -9007199254740991;
export const uploadGetFilesByIdResponseWidthMax = 9007199254740991;

export const uploadGetFilesByIdResponseHeightMin = -9007199254740991;
export const uploadGetFilesByIdResponseHeightMax = 9007199254740991;

export const uploadGetFilesByIdResponse = zod.object({
  id: zod.number().max(uploadGetFilesByIdResponseIdMax),
  documentId: zod.uuid().regex(uploadGetFilesByIdResponseDocumentIdRegExp),
  name: zod.string(),
  alternativeText: zod.union([zod.string(), zod.null()]).optional(),
  caption: zod.union([zod.string(), zod.null()]).optional(),
  width: zod
    .number()
    .min(uploadGetFilesByIdResponseWidthMin)
    .max(uploadGetFilesByIdResponseWidthMax)
    .optional(),
  height: zod
    .number()
    .min(uploadGetFilesByIdResponseHeightMin)
    .max(uploadGetFilesByIdResponseHeightMax)
    .optional(),
  formats: zod.record(zod.string(), zod.unknown()).optional(),
  hash: zod.string(),
  ext: zod.string().optional(),
  mime: zod.string(),
  size: zod.number(),
  url: zod.string(),
  previewUrl: zod.union([zod.string(), zod.null()]).optional(),
  folder: zod.number().optional(),
  folderPath: zod.string(),
  provider: zod.string(),
  provider_metadata: zod
    .union([zod.record(zod.string(), zod.unknown()), zod.null()])
    .optional(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
  createdBy: zod.number().optional(),
  updatedBy: zod.number().optional(),
});

export const uploadDeleteFilesByIdPathIdMax = 9007199254740991;

export const uploadDeleteFilesByIdParams = zod.object({
  id: zod.number().max(uploadDeleteFilesByIdPathIdMax),
});

export const uploadDeleteFilesByIdResponseIdMax = 9007199254740991;

export const uploadDeleteFilesByIdResponseDocumentIdRegExp = new RegExp(
  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$",
);
export const uploadDeleteFilesByIdResponseWidthMin = -9007199254740991;
export const uploadDeleteFilesByIdResponseWidthMax = 9007199254740991;

export const uploadDeleteFilesByIdResponseHeightMin = -9007199254740991;
export const uploadDeleteFilesByIdResponseHeightMax = 9007199254740991;

export const uploadDeleteFilesByIdResponse = zod.object({
  id: zod.number().max(uploadDeleteFilesByIdResponseIdMax),
  documentId: zod.uuid().regex(uploadDeleteFilesByIdResponseDocumentIdRegExp),
  name: zod.string(),
  alternativeText: zod.union([zod.string(), zod.null()]).optional(),
  caption: zod.union([zod.string(), zod.null()]).optional(),
  width: zod
    .number()
    .min(uploadDeleteFilesByIdResponseWidthMin)
    .max(uploadDeleteFilesByIdResponseWidthMax)
    .optional(),
  height: zod
    .number()
    .min(uploadDeleteFilesByIdResponseHeightMin)
    .max(uploadDeleteFilesByIdResponseHeightMax)
    .optional(),
  formats: zod.record(zod.string(), zod.unknown()).optional(),
  hash: zod.string(),
  ext: zod.string().optional(),
  mime: zod.string(),
  size: zod.number(),
  url: zod.string(),
  previewUrl: zod.union([zod.string(), zod.null()]).optional(),
  folder: zod.number().optional(),
  folderPath: zod.string(),
  provider: zod.string(),
  provider_metadata: zod
    .union([zod.record(zod.string(), zod.unknown()), zod.null()])
    .optional(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
  createdBy: zod.number().optional(),
  updatedBy: zod.number().optional(),
});
