/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
export type ContentTypeBuilderGetContentTypesParams = {
  kind: ContentTypeBuilderGetContentTypesKind;
};

export type ContentTypeBuilderGetContentTypesKind =
  (typeof ContentTypeBuilderGetContentTypesKind)[keyof typeof ContentTypeBuilderGetContentTypesKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentTypeBuilderGetContentTypesKind = {
  collectionType: "collectionType",
  singleType: "singleType",
} as const;

export type ContentTypeBuilderGetContentTypes200DataItemSchemaKind =
  (typeof ContentTypeBuilderGetContentTypes200DataItemSchemaKind)[keyof typeof ContentTypeBuilderGetContentTypes200DataItemSchemaKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentTypeBuilderGetContentTypes200DataItemSchemaKind = {
  collectionType: "collectionType",
  singleType: "singleType",
} as const;

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOf =
  {
    type: "media";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfPluginOptions;
    multiple: boolean;
    required?: boolean;
    allowedTypes?: string[];
  };

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfThreePluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfThreeTargetAttribute =
  string | null;

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfThree =
  {
    type: "relation";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfThreePluginOptions;
    relation: string;
    /** @pattern ^((strapi|admin)::[\w-]+|(api|plugin)::[\w-]+\.[\w-]+)$ */
    target: string;
    targetAttribute: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfThreeTargetAttribute;
    autoPopulate?: boolean;
    mappedBy?: string;
    inversedBy?: string;
  };

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfSixPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfSix =
  {
    type: "component";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfSixPluginOptions;
    component: string;
    repeatable: boolean;
    required?: boolean;
    min?: number;
    max?: number;
  };

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfEightPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfEight =
  {
    type: "dynamiczone";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfEightPluginOptions;
    components: string[];
    required?: boolean;
    min?: number;
    max?: number;
  };

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnezeroPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnezero =
  {
    type: "uid";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnezeroPluginOptions;
    targetField?: string;
  };

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwoMin =
  number | string;

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwoMax =
  number | string;

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwoPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwo =
  {
    type: string;
    required?: boolean;
    unique?: boolean;
    default?: unknown;
    min?: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwoMin;
    max?: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwoMax;
    minLength?: number;
    maxLength?: number;
    enum?: string[];
    regex?: string;
    private?: boolean;
    configurable?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwoPluginOptions;
  };

export type ContentTypeBuilderGetContentTypes200DataItemSchemaAttributes = {
  [key: string]:
    | ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOf
    | ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfThree
    | ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfSix
    | ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfEight
    | ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnezero
    | ContentTypeBuilderGetContentTypes200DataItemSchemaAttributesAnyOfOnetwo;
};

export type ContentTypeBuilderGetContentTypes200DataItemSchemaRestrictRelationsTo =
  string[] | null;

export type ContentTypeBuilderGetContentTypes200DataItemSchemaPluginOptions = {
  [key: string]: unknown;
};

export type ContentTypeBuilderGetContentTypes200DataItemSchemaOptions = {
  [key: string]: unknown;
};

export type ContentTypeBuilderGetContentTypes200DataItemSchema = {
  displayName: string;
  singularName: string;
  pluralName: string;
  description: string;
  draftAndPublish: boolean;
  kind: ContentTypeBuilderGetContentTypes200DataItemSchemaKind;
  collectionName?: string;
  attributes: ContentTypeBuilderGetContentTypes200DataItemSchemaAttributes;
  visible: boolean;
  restrictRelationsTo: ContentTypeBuilderGetContentTypes200DataItemSchemaRestrictRelationsTo;
  pluginOptions?: ContentTypeBuilderGetContentTypes200DataItemSchemaPluginOptions;
  options?: ContentTypeBuilderGetContentTypes200DataItemSchemaOptions;
  reviewWorkflows?: boolean;
  populateCreatorFields?: boolean;
  comment?: string;
  version?: string;
};

export type ContentTypeBuilderGetContentTypes200DataItem = {
  /** @pattern ^((strapi|admin)::[\w-]+|(api|plugin)::[\w-]+\.[\w-]+)$ */
  uid: string;
  plugin?: string;
  apiID: string;
  schema: ContentTypeBuilderGetContentTypes200DataItemSchema;
};

export type ContentTypeBuilderGetContentTypes200 = {
  data: ContentTypeBuilderGetContentTypes200DataItem[];
};

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaKind =
  (typeof ContentTypeBuilderGetContentTypesByUid200DataSchemaKind)[keyof typeof ContentTypeBuilderGetContentTypesByUid200DataSchemaKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentTypeBuilderGetContentTypesByUid200DataSchemaKind = {
  collectionType: "collectionType",
  singleType: "singleType",
} as const;

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOf =
  {
    type: "media";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfPluginOptions;
    multiple: boolean;
    required?: boolean;
    allowedTypes?: string[];
  };

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfThreePluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfThreeTargetAttribute =
  string | null;

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfThree =
  {
    type: "relation";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfThreePluginOptions;
    relation: string;
    /** @pattern ^((strapi|admin)::[\w-]+|(api|plugin)::[\w-]+\.[\w-]+)$ */
    target: string;
    targetAttribute: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfThreeTargetAttribute;
    autoPopulate?: boolean;
    mappedBy?: string;
    inversedBy?: string;
  };

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfSixPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfSix =
  {
    type: "component";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfSixPluginOptions;
    component: string;
    repeatable: boolean;
    required?: boolean;
    min?: number;
    max?: number;
  };

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfEightPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfEight =
  {
    type: "dynamiczone";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfEightPluginOptions;
    components: string[];
    required?: boolean;
    min?: number;
    max?: number;
  };

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnezeroPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnezero =
  {
    type: "uid";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnezeroPluginOptions;
    targetField?: string;
  };

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwoMin =
  number | string;

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwoMax =
  number | string;

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwoPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwo =
  {
    type: string;
    required?: boolean;
    unique?: boolean;
    default?: unknown;
    min?: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwoMin;
    max?: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwoMax;
    minLength?: number;
    maxLength?: number;
    enum?: string[];
    regex?: string;
    private?: boolean;
    configurable?: boolean;
    pluginOptions?: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwoPluginOptions;
  };

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributes = {
  [key: string]:
    | ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOf
    | ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfThree
    | ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfSix
    | ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfEight
    | ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnezero
    | ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributesAnyOfOnetwo;
};

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaRestrictRelationsTo =
  string[] | null;

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaPluginOptions = {
  [key: string]: unknown;
};

export type ContentTypeBuilderGetContentTypesByUid200DataSchemaOptions = {
  [key: string]: unknown;
};

export type ContentTypeBuilderGetContentTypesByUid200DataSchema = {
  displayName: string;
  singularName: string;
  pluralName: string;
  description: string;
  draftAndPublish: boolean;
  kind: ContentTypeBuilderGetContentTypesByUid200DataSchemaKind;
  collectionName?: string;
  attributes: ContentTypeBuilderGetContentTypesByUid200DataSchemaAttributes;
  visible: boolean;
  restrictRelationsTo: ContentTypeBuilderGetContentTypesByUid200DataSchemaRestrictRelationsTo;
  pluginOptions?: ContentTypeBuilderGetContentTypesByUid200DataSchemaPluginOptions;
  options?: ContentTypeBuilderGetContentTypesByUid200DataSchemaOptions;
  reviewWorkflows?: boolean;
  populateCreatorFields?: boolean;
  comment?: string;
  version?: string;
};

export type ContentTypeBuilderGetContentTypesByUid200Data = {
  /** @pattern ^((strapi|admin)::[\w-]+|(api|plugin)::[\w-]+\.[\w-]+)$ */
  uid: string;
  plugin?: string;
  apiID: string;
  schema: ContentTypeBuilderGetContentTypesByUid200DataSchema;
};

export type ContentTypeBuilderGetContentTypesByUid200 = {
  data: ContentTypeBuilderGetContentTypesByUid200Data;
};

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOf = {
  type: "media";
  configurable?: false;
  private?: boolean;
  pluginOptions?: ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfPluginOptions;
  multiple: boolean;
  required?: boolean;
  allowedTypes?: string[];
};

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThreePluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThreeTargetAttribute =
  string | null;

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThree =
  {
    type: "relation";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThreePluginOptions;
    relation: string;
    /** @pattern ^((strapi|admin)::[\w-]+|(api|plugin)::[\w-]+\.[\w-]+)$ */
    target: string;
    targetAttribute: ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThreeTargetAttribute;
    autoPopulate?: boolean;
    mappedBy?: string;
    inversedBy?: string;
  };

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfSixPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfSix =
  {
    type: "component";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfSixPluginOptions;
    component: string;
    repeatable: boolean;
    required?: boolean;
    min?: number;
    max?: number;
  };

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfEightPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfEight =
  {
    type: "dynamiczone";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfEightPluginOptions;
    components: string[];
    required?: boolean;
    min?: number;
    max?: number;
  };

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnezeroPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnezero =
  {
    type: "uid";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnezeroPluginOptions;
    targetField?: string;
  };

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwoMin =
  number | string;

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwoMax =
  number | string;

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwoPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwo =
  {
    type: string;
    required?: boolean;
    unique?: boolean;
    default?: unknown;
    min?: ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwoMin;
    max?: ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwoMax;
    minLength?: number;
    maxLength?: number;
    enum?: string[];
    regex?: string;
    private?: boolean;
    configurable?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwoPluginOptions;
  };

export type ContentTypeBuilderGetComponents200DataItemSchemaAttributes = {
  [key: string]:
    | ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOf
    | ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfThree
    | ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfSix
    | ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfEight
    | ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnezero
    | ContentTypeBuilderGetComponents200DataItemSchemaAttributesAnyOfOnetwo;
};

export type ContentTypeBuilderGetComponents200DataItemSchemaPluginOptions = {
  [key: string]: unknown;
};

export type ContentTypeBuilderGetComponents200DataItemSchema = {
  displayName: string;
  description: string;
  icon?: string;
  connection?: string;
  collectionName?: string;
  attributes: ContentTypeBuilderGetComponents200DataItemSchemaAttributes;
  pluginOptions?: ContentTypeBuilderGetComponents200DataItemSchemaPluginOptions;
};

export type ContentTypeBuilderGetComponents200DataItem = {
  /** @pattern ^[\w-]+\.[\w-]+$ */
  uid: string;
  category: string;
  apiId: string;
  schema: ContentTypeBuilderGetComponents200DataItemSchema;
};

export type ContentTypeBuilderGetComponents200 = {
  data: ContentTypeBuilderGetComponents200DataItem[];
};

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOf = {
  type: "media";
  configurable?: false;
  private?: boolean;
  pluginOptions?: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfPluginOptions;
  multiple: boolean;
  required?: boolean;
  allowedTypes?: string[];
};

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfThreePluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfThreeTargetAttribute =
  string | null;

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfThree =
  {
    type: "relation";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfThreePluginOptions;
    relation: string;
    /** @pattern ^((strapi|admin)::[\w-]+|(api|plugin)::[\w-]+\.[\w-]+)$ */
    target: string;
    targetAttribute: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfThreeTargetAttribute;
    autoPopulate?: boolean;
    mappedBy?: string;
    inversedBy?: string;
  };

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfSixPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfSix =
  {
    type: "component";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfSixPluginOptions;
    component: string;
    repeatable: boolean;
    required?: boolean;
    min?: number;
    max?: number;
  };

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfEightPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfEight =
  {
    type: "dynamiczone";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfEightPluginOptions;
    components: string[];
    required?: boolean;
    min?: number;
    max?: number;
  };

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnezeroPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnezero =
  {
    type: "uid";
    configurable?: false;
    private?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnezeroPluginOptions;
    targetField?: string;
  };

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnetwoMin =
  number | string;

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnetwoMax =
  number | string;

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnetwoPluginOptions =
  { [key: string]: unknown };

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnetwo =
  {
    type: string;
    required?: boolean;
    unique?: boolean;
    default?: unknown;
    min?: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnetwoMin;
    max?: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnetwoMax;
    minLength?: number;
    maxLength?: number;
    enum?: string[];
    regex?: string;
    private?: boolean;
    configurable?: boolean;
    pluginOptions?: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnetwoPluginOptions;
  };

export type ContentTypeBuilderGetComponentsByUid200DataSchemaAttributes = {
  [key: string]:
    | ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOf
    | ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfThree
    | ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfSix
    | ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfEight
    | ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnezero
    | ContentTypeBuilderGetComponentsByUid200DataSchemaAttributesAnyOfOnetwo;
};

export type ContentTypeBuilderGetComponentsByUid200DataSchemaPluginOptions = {
  [key: string]: unknown;
};

export type ContentTypeBuilderGetComponentsByUid200DataSchema = {
  displayName: string;
  description: string;
  icon?: string;
  connection?: string;
  collectionName?: string;
  attributes: ContentTypeBuilderGetComponentsByUid200DataSchemaAttributes;
  pluginOptions?: ContentTypeBuilderGetComponentsByUid200DataSchemaPluginOptions;
};

export type ContentTypeBuilderGetComponentsByUid200Data = {
  /** @pattern ^[\w-]+\.[\w-]+$ */
  uid: string;
  category: string;
  apiId: string;
  schema: ContentTypeBuilderGetComponentsByUid200DataSchema;
};

export type ContentTypeBuilderGetComponentsByUid200 = {
  data: ContentTypeBuilderGetComponentsByUid200Data;
};

export type UploadPostParams = {
  /**
   * @maximum 9007199254740991
   */
  id?: number;
};

export type UploadPost200AnyOfAlternativeText = string | null;

export type UploadPost200AnyOfCaption = string | null;

export type UploadPost200AnyOfFormats = { [key: string]: unknown };

export type UploadPost200AnyOfPreviewUrl = string | null;

export type UploadPost200AnyOfProviderMetadataAnyOf = {
  [key: string]: unknown;
};

export type UploadPost200AnyOfProviderMetadata =
  UploadPost200AnyOfProviderMetadataAnyOf | null;

export type UploadPost200AnyOf = {
  /**
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  documentId: string;
  name: string;
  alternativeText?: UploadPost200AnyOfAlternativeText;
  caption?: UploadPost200AnyOfCaption;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  width?: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  height?: number;
  formats?: UploadPost200AnyOfFormats;
  hash: string;
  ext?: string;
  mime: string;
  size: number;
  url: string;
  previewUrl?: UploadPost200AnyOfPreviewUrl;
  folder?: number;
  folderPath: string;
  provider: string;
  provider_metadata?: UploadPost200AnyOfProviderMetadata;
  createdAt: string;
  updatedAt: string;
  createdBy?: number;
  updatedBy?: number;
};

export type UploadPost200AnyOfEightItemAlternativeText = string | null;

export type UploadPost200AnyOfEightItemCaption = string | null;

export type UploadPost200AnyOfEightItemFormats = { [key: string]: unknown };

export type UploadPost200AnyOfEightItemPreviewUrl = string | null;

export type UploadPost200AnyOfEightItemProviderMetadataAnyOf = {
  [key: string]: unknown;
};

export type UploadPost200AnyOfEightItemProviderMetadata =
  UploadPost200AnyOfEightItemProviderMetadataAnyOf | null;

export type UploadPost200AnyOfEightItem = {
  /**
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  documentId: string;
  name: string;
  alternativeText?: UploadPost200AnyOfEightItemAlternativeText;
  caption?: UploadPost200AnyOfEightItemCaption;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  width?: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  height?: number;
  formats?: UploadPost200AnyOfEightItemFormats;
  hash: string;
  ext?: string;
  mime: string;
  size: number;
  url: string;
  previewUrl?: UploadPost200AnyOfEightItemPreviewUrl;
  folder?: number;
  folderPath: string;
  provider: string;
  provider_metadata?: UploadPost200AnyOfEightItemProviderMetadata;
  createdAt: string;
  updatedAt: string;
  createdBy?: number;
  updatedBy?: number;
};

export type UploadPost200 = UploadPost200AnyOf | UploadPost200AnyOfEightItem[];

export type UploadGetFilesParams = {
  /**
   * Select specific fields to return in the response
   */
  fields?: string | string[];
  /**
   * Specify which relations to populate in the response
   */
  populate?: "*" | string | string[] | UploadGetFilesPopulateAnyOf;
  /**
   * Sort the results by specified fields
   */
  sort?:
    | string
    | string[]
    | UploadGetFilesSortAnyOf
    | UploadGetFilesSortAnyOfTwoItem[];
  /**
   * Pagination parameters
   */
  pagination?: UploadGetFilesPaginationAllOf & UploadGetFilesPaginationAllOfTwo;
  /**
   * Apply filters to the query
   */
  filters?: { [key: string]: unknown };
};

export type UploadGetFilesPopulateAnyOf = { [key: string]: unknown };

export type UploadGetFilesSortAnyOf = { [key: string]: "asc" | "desc" };

export type UploadGetFilesSortAnyOfTwoItem = { [key: string]: "asc" | "desc" };

export type UploadGetFilesPaginationAllOf = {
  /** Include total count in response */
  withCount?: boolean;
};

/**
 * Page-based pagination
 */
export type UploadGetFilesPaginationAllOfTwoAnyOf = {
  /**
   * Page number (1-based)
   * @maximum 9007199254740991
   */
  page: number;
  /**
   * Number of entries per page
   * @maximum 9007199254740991
   */
  pageSize: number;
};

/**
 * Offset-based pagination
 */
export type UploadGetFilesPaginationAllOfTwoAnyOfTwo = {
  /**
   * Number of entries to skip
   * @minimum 0
   * @maximum 9007199254740991
   */
  start: number;
  /**
   * Maximum number of entries to return
   * @maximum 9007199254740991
   */
  limit: number;
};

export type UploadGetFilesPaginationAllOfTwo =
  | UploadGetFilesPaginationAllOfTwoAnyOf
  | UploadGetFilesPaginationAllOfTwoAnyOfTwo;

export type UploadGetFiles200ItemAlternativeText = string | null;

export type UploadGetFiles200ItemCaption = string | null;

export type UploadGetFiles200ItemFormats = { [key: string]: unknown };

export type UploadGetFiles200ItemPreviewUrl = string | null;

export type UploadGetFiles200ItemProviderMetadataAnyOf = {
  [key: string]: unknown;
};

export type UploadGetFiles200ItemProviderMetadata =
  UploadGetFiles200ItemProviderMetadataAnyOf | null;

export type UploadGetFiles200Item = {
  /**
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  documentId: string;
  name: string;
  alternativeText?: UploadGetFiles200ItemAlternativeText;
  caption?: UploadGetFiles200ItemCaption;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  width?: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  height?: number;
  formats?: UploadGetFiles200ItemFormats;
  hash: string;
  ext?: string;
  mime: string;
  size: number;
  url: string;
  previewUrl?: UploadGetFiles200ItemPreviewUrl;
  folder?: number;
  folderPath: string;
  provider: string;
  provider_metadata?: UploadGetFiles200ItemProviderMetadata;
  createdAt: string;
  updatedAt: string;
  createdBy?: number;
  updatedBy?: number;
};

export type UploadGetFilesByIdParams = {
  /**
   * Select specific fields to return in the response
   */
  fields?: string | string[];
  /**
   * Specify which relations to populate in the response
   */
  populate?: "*" | string | string[] | UploadGetFilesByIdPopulateAnyOf;
};

export type UploadGetFilesByIdPopulateAnyOf = { [key: string]: unknown };

export type UploadGetFilesById200AlternativeText = string | null;

export type UploadGetFilesById200Caption = string | null;

export type UploadGetFilesById200Formats = { [key: string]: unknown };

export type UploadGetFilesById200PreviewUrl = string | null;

export type UploadGetFilesById200ProviderMetadataAnyOf = {
  [key: string]: unknown;
};

export type UploadGetFilesById200ProviderMetadata =
  UploadGetFilesById200ProviderMetadataAnyOf | null;

export type UploadGetFilesById200 = {
  /**
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  documentId: string;
  name: string;
  alternativeText?: UploadGetFilesById200AlternativeText;
  caption?: UploadGetFilesById200Caption;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  width?: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  height?: number;
  formats?: UploadGetFilesById200Formats;
  hash: string;
  ext?: string;
  mime: string;
  size: number;
  url: string;
  previewUrl?: UploadGetFilesById200PreviewUrl;
  folder?: number;
  folderPath: string;
  provider: string;
  provider_metadata?: UploadGetFilesById200ProviderMetadata;
  createdAt: string;
  updatedAt: string;
  createdBy?: number;
  updatedBy?: number;
};

export type UploadDeleteFilesById200AlternativeText = string | null;

export type UploadDeleteFilesById200Caption = string | null;

export type UploadDeleteFilesById200Formats = { [key: string]: unknown };

export type UploadDeleteFilesById200PreviewUrl = string | null;

export type UploadDeleteFilesById200ProviderMetadataAnyOf = {
  [key: string]: unknown;
};

export type UploadDeleteFilesById200ProviderMetadata =
  UploadDeleteFilesById200ProviderMetadataAnyOf | null;

export type UploadDeleteFilesById200 = {
  /**
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  documentId: string;
  name: string;
  alternativeText?: UploadDeleteFilesById200AlternativeText;
  caption?: UploadDeleteFilesById200Caption;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  width?: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  height?: number;
  formats?: UploadDeleteFilesById200Formats;
  hash: string;
  ext?: string;
  mime: string;
  size: number;
  url: string;
  previewUrl?: UploadDeleteFilesById200PreviewUrl;
  folder?: number;
  folderPath: string;
  provider: string;
  provider_metadata?: UploadDeleteFilesById200ProviderMetadata;
  createdAt: string;
  updatedAt: string;
  createdBy?: number;
  updatedBy?: number;
};

export type I18nGetLocales200ItemPublishedAt = string | null;

export type I18nGetLocales200Item = {
  /**
   * @maximum 9007199254740991
   */
  id: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000)$ */
  documentId: string;
  name: string;
  /**
   * @minLength 2
   * @maxLength 2
   */
  code: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: I18nGetLocales200ItemPublishedAt;
  isDefault: boolean;
};

export type UsersPermissionsPostAuthLocalBody = {
  identifier: string;
  password: string;
};

export type UsersPermissionsPostAuthLocal200UserRoleAnyOfDescription =
  | string
  | null;

export type UsersPermissionsPostAuthLocal200UserRoleAnyOf = {
  id: number;
  name: string;
  description: UsersPermissionsPostAuthLocal200UserRoleAnyOfDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
};

export type UsersPermissionsPostAuthLocal200UserRole =
  | number
  | UsersPermissionsPostAuthLocal200UserRoleAnyOf;

export type UsersPermissionsPostAuthLocal200User = {
  id: number;
  documentId: string;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  role?: UsersPermissionsPostAuthLocal200UserRole;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};

export type UsersPermissionsPostAuthLocal200 = {
  jwt: string;
  refreshToken?: string;
  user: UsersPermissionsPostAuthLocal200User;
};

export type UsersPermissionsPostAuthLocalRegisterBody = {
  username: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  password: string;
};

export type UsersPermissionsPostAuthLocalRegister200AnyOfUserRoleAnyOfDescription =
  string | null;

export type UsersPermissionsPostAuthLocalRegister200AnyOfUserRoleAnyOf = {
  id: number;
  name: string;
  description: UsersPermissionsPostAuthLocalRegister200AnyOfUserRoleAnyOfDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
};

export type UsersPermissionsPostAuthLocalRegister200AnyOfUserRole =
  | number
  | UsersPermissionsPostAuthLocalRegister200AnyOfUserRoleAnyOf;

export type UsersPermissionsPostAuthLocalRegister200AnyOfUser = {
  id: number;
  documentId: string;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  role?: UsersPermissionsPostAuthLocalRegister200AnyOfUserRole;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};

export type UsersPermissionsPostAuthLocalRegister200AnyOf = {
  jwt: string;
  refreshToken?: string;
  user: UsersPermissionsPostAuthLocalRegister200AnyOfUser;
};

export type UsersPermissionsPostAuthLocalRegister200AnyOfSixUserRoleAnyOfDescription =
  string | null;

export type UsersPermissionsPostAuthLocalRegister200AnyOfSixUserRoleAnyOf = {
  id: number;
  name: string;
  description: UsersPermissionsPostAuthLocalRegister200AnyOfSixUserRoleAnyOfDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
};

export type UsersPermissionsPostAuthLocalRegister200AnyOfSixUserRole =
  | number
  | UsersPermissionsPostAuthLocalRegister200AnyOfSixUserRoleAnyOf;

export type UsersPermissionsPostAuthLocalRegister200AnyOfSixUser = {
  id: number;
  documentId: string;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  role?: UsersPermissionsPostAuthLocalRegister200AnyOfSixUserRole;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};

export type UsersPermissionsPostAuthLocalRegister200AnyOfSix = {
  user: UsersPermissionsPostAuthLocalRegister200AnyOfSixUser;
};

export type UsersPermissionsPostAuthLocalRegister200 =
  | UsersPermissionsPostAuthLocalRegister200AnyOf
  | UsersPermissionsPostAuthLocalRegister200AnyOfSix;

export type UsersPermissionsGetAuthByProviderCallback200UserRoleAnyOfDescription =
  string | null;

export type UsersPermissionsGetAuthByProviderCallback200UserRoleAnyOf = {
  id: number;
  name: string;
  description: UsersPermissionsGetAuthByProviderCallback200UserRoleAnyOfDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
};

export type UsersPermissionsGetAuthByProviderCallback200UserRole =
  | number
  | UsersPermissionsGetAuthByProviderCallback200UserRoleAnyOf;

export type UsersPermissionsGetAuthByProviderCallback200User = {
  id: number;
  documentId: string;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  role?: UsersPermissionsGetAuthByProviderCallback200UserRole;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};

export type UsersPermissionsGetAuthByProviderCallback200 = {
  jwt: string;
  refreshToken?: string;
  user: UsersPermissionsGetAuthByProviderCallback200User;
};

export type UsersPermissionsPostAuthForgotPasswordBody = {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
};

export type UsersPermissionsPostAuthForgotPassword200 = {
  ok: boolean;
};

export type UsersPermissionsPostAuthResetPasswordBody = {
  code: string;
  password: string;
  passwordConfirmation: string;
};

export type UsersPermissionsPostAuthResetPassword200UserRoleAnyOfDescription =
  | string
  | null;

export type UsersPermissionsPostAuthResetPassword200UserRoleAnyOf = {
  id: number;
  name: string;
  description: UsersPermissionsPostAuthResetPassword200UserRoleAnyOfDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
};

export type UsersPermissionsPostAuthResetPassword200UserRole =
  | number
  | UsersPermissionsPostAuthResetPassword200UserRoleAnyOf;

export type UsersPermissionsPostAuthResetPassword200User = {
  id: number;
  documentId: string;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  role?: UsersPermissionsPostAuthResetPassword200UserRole;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};

export type UsersPermissionsPostAuthResetPassword200 = {
  jwt: string;
  refreshToken?: string;
  user: UsersPermissionsPostAuthResetPassword200User;
};

export type UsersPermissionsPostAuthSendEmailConfirmationBody = {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
};

export type UsersPermissionsPostAuthSendEmailConfirmation200 = {
  email: string;
  sent: boolean;
};

export type UsersPermissionsPostAuthChangePasswordBody = {
  currentPassword: string;
  password: string;
  passwordConfirmation: string;
};

export type UsersPermissionsPostAuthChangePassword200UserRoleAnyOfDescription =
  | string
  | null;

export type UsersPermissionsPostAuthChangePassword200UserRoleAnyOf = {
  id: number;
  name: string;
  description: UsersPermissionsPostAuthChangePassword200UserRoleAnyOfDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
};

export type UsersPermissionsPostAuthChangePassword200UserRole =
  | number
  | UsersPermissionsPostAuthChangePassword200UserRoleAnyOf;

export type UsersPermissionsPostAuthChangePassword200User = {
  id: number;
  documentId: string;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  role?: UsersPermissionsPostAuthChangePassword200UserRole;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};

export type UsersPermissionsPostAuthChangePassword200 = {
  jwt: string;
  refreshToken?: string;
  user: UsersPermissionsPostAuthChangePassword200User;
};

export type UsersPermissionsGetUsersCountParams = {
  /**
   * Apply filters to the query
   */
  filters?: { [key: string]: unknown };
};

export type UsersPermissionsGetUsersParams = {
  /**
   * Select specific fields to return in the response
   */
  fields?: string | string[];
  /**
   * Specify which relations to populate in the response
   */
  populate?: "*" | string | string[] | UsersPermissionsGetUsersPopulateAnyOf;
  /**
   * Sort the results by specified fields
   */
  sort?:
    | string
    | string[]
    | UsersPermissionsGetUsersSortAnyOf
    | UsersPermissionsGetUsersSortAnyOfTwoItem[];
  /**
   * Pagination parameters
   */
  pagination?: UsersPermissionsGetUsersPaginationAllOf &
    UsersPermissionsGetUsersPaginationAllOfTwo;
  /**
   * Apply filters to the query
   */
  filters?: { [key: string]: unknown };
};

export type UsersPermissionsGetUsersPopulateAnyOf = { [key: string]: unknown };

export type UsersPermissionsGetUsersSortAnyOf = {
  [key: string]: "asc" | "desc";
};

export type UsersPermissionsGetUsersSortAnyOfTwoItem = {
  [key: string]: "asc" | "desc";
};

export type UsersPermissionsGetUsersPaginationAllOf = {
  /** Include total count in response */
  withCount?: boolean;
};

/**
 * Page-based pagination
 */
export type UsersPermissionsGetUsersPaginationAllOfTwoAnyOf = {
  /**
   * Page number (1-based)
   * @maximum 9007199254740991
   */
  page: number;
  /**
   * Number of entries per page
   * @maximum 9007199254740991
   */
  pageSize: number;
};

/**
 * Offset-based pagination
 */
export type UsersPermissionsGetUsersPaginationAllOfTwoAnyOfTwo = {
  /**
   * Number of entries to skip
   * @minimum 0
   * @maximum 9007199254740991
   */
  start: number;
  /**
   * Maximum number of entries to return
   * @maximum 9007199254740991
   */
  limit: number;
};

export type UsersPermissionsGetUsersPaginationAllOfTwo =
  | UsersPermissionsGetUsersPaginationAllOfTwoAnyOf
  | UsersPermissionsGetUsersPaginationAllOfTwoAnyOfTwo;

export type UsersPermissionsGetUsers200ItemRoleAnyOfDescription = string | null;

export type UsersPermissionsGetUsers200ItemRoleAnyOf = {
  id: number;
  name: string;
  description: UsersPermissionsGetUsers200ItemRoleAnyOfDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
};

export type UsersPermissionsGetUsers200ItemRole =
  | number
  | UsersPermissionsGetUsers200ItemRoleAnyOf;

export type UsersPermissionsGetUsers200Item = {
  id: number;
  documentId: string;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  role?: UsersPermissionsGetUsers200ItemRole;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};

export type UsersPermissionsPostUsersBody = {
  username: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  password: string;
  role?: number;
};

export type UsersPermissionsPostUsers200RoleAnyOfDescription = string | null;

export type UsersPermissionsPostUsers200RoleAnyOf = {
  id: number;
  name: string;
  description: UsersPermissionsPostUsers200RoleAnyOfDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
};

export type UsersPermissionsPostUsers200Role =
  | number
  | UsersPermissionsPostUsers200RoleAnyOf;

export type UsersPermissionsPostUsers200 = {
  id: number;
  documentId: string;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  role?: UsersPermissionsPostUsers200Role;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};

export type UsersPermissionsGetUsersMeParams = {
  /**
   * Select specific fields to return in the response
   */
  fields?: string | string[];
  /**
   * Specify which relations to populate in the response
   */
  populate?: "*" | string | string[] | UsersPermissionsGetUsersMePopulateAnyOf;
};

export type UsersPermissionsGetUsersMePopulateAnyOf = {
  [key: string]: unknown;
};

export type UsersPermissionsGetUsersMe200RoleAnyOfDescription = string | null;

export type UsersPermissionsGetUsersMe200RoleAnyOf = {
  id: number;
  name: string;
  description: UsersPermissionsGetUsersMe200RoleAnyOfDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
};

export type UsersPermissionsGetUsersMe200Role =
  | number
  | UsersPermissionsGetUsersMe200RoleAnyOf;

export type UsersPermissionsGetUsersMe200 = {
  id: number;
  documentId: string;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  role?: UsersPermissionsGetUsersMe200Role;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};

export type UsersPermissionsGetUsersByIdParams = {
  /**
   * Select specific fields to return in the response
   */
  fields?: string | string[];
  /**
   * Specify which relations to populate in the response
   */
  populate?:
    | "*"
    | string
    | string[]
    | UsersPermissionsGetUsersByIdPopulateAnyOf;
};

export type UsersPermissionsGetUsersByIdPopulateAnyOf = {
  [key: string]: unknown;
};

export type UsersPermissionsGetUsersById200RoleAnyOfDescription = string | null;

export type UsersPermissionsGetUsersById200RoleAnyOf = {
  id: number;
  name: string;
  description: UsersPermissionsGetUsersById200RoleAnyOfDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
};

export type UsersPermissionsGetUsersById200Role =
  | number
  | UsersPermissionsGetUsersById200RoleAnyOf;

export type UsersPermissionsGetUsersById200 = {
  id: number;
  documentId: string;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  role?: UsersPermissionsGetUsersById200Role;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};

export type UsersPermissionsPutUsersByIdBody = {
  username?: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email?: string;
  password?: string;
  role?: number;
};

export type UsersPermissionsPutUsersById200RoleAnyOfDescription = string | null;

export type UsersPermissionsPutUsersById200RoleAnyOf = {
  id: number;
  name: string;
  description: UsersPermissionsPutUsersById200RoleAnyOfDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
};

export type UsersPermissionsPutUsersById200Role =
  | number
  | UsersPermissionsPutUsersById200RoleAnyOf;

export type UsersPermissionsPutUsersById200 = {
  id: number;
  documentId: string;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  role?: UsersPermissionsPutUsersById200Role;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};

export type UsersPermissionsDeleteUsersById200RoleAnyOfDescription =
  | string
  | null;

export type UsersPermissionsDeleteUsersById200RoleAnyOf = {
  id: number;
  name: string;
  description: UsersPermissionsDeleteUsersById200RoleAnyOfDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
};

export type UsersPermissionsDeleteUsersById200Role =
  | number
  | UsersPermissionsDeleteUsersById200RoleAnyOf;

export type UsersPermissionsDeleteUsersById200 = {
  id: number;
  documentId: string;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  role?: UsersPermissionsDeleteUsersById200Role;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
};

export type UsersPermissionsGetRolesById200RoleDescription = string | null;

export type UsersPermissionsGetRolesById200RolePermissionsControllers = {
  [key: string]: {
    [key: string]: {
      enabled: boolean;
      policy: string;
    };
  };
};

export type UsersPermissionsGetRolesById200RolePermissions = {
  [key: string]: {
    controllers: UsersPermissionsGetRolesById200RolePermissionsControllers;
  };
};

export type UsersPermissionsGetRolesById200Role = {
  id: number;
  documentId: string;
  name: string;
  description: UsersPermissionsGetRolesById200RoleDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  nb_users?: number;
  permissions?: UsersPermissionsGetRolesById200RolePermissions;
  users?: unknown[];
};

export type UsersPermissionsGetRolesById200 = {
  role: UsersPermissionsGetRolesById200Role;
};

export type UsersPermissionsGetRoles200RolesItemDescription = string | null;

export type UsersPermissionsGetRoles200RolesItemPermissionsControllers = {
  [key: string]: {
    [key: string]: {
      enabled: boolean;
      policy: string;
    };
  };
};

export type UsersPermissionsGetRoles200RolesItemPermissions = {
  [key: string]: {
    controllers: UsersPermissionsGetRoles200RolesItemPermissionsControllers;
  };
};

export type UsersPermissionsGetRoles200RolesItem = {
  id: number;
  documentId: string;
  name: string;
  description: UsersPermissionsGetRoles200RolesItemDescription;
  type: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  nb_users?: number;
  permissions?: UsersPermissionsGetRoles200RolesItemPermissions;
  users?: unknown[];
};

export type UsersPermissionsGetRoles200 = {
  roles: UsersPermissionsGetRoles200RolesItem[];
};

export type UsersPermissionsPostRolesBodyPermissions = {
  [key: string]: unknown;
};

export type UsersPermissionsPostRolesBody = {
  name: string;
  description?: string;
  type: string;
  permissions?: UsersPermissionsPostRolesBodyPermissions;
};

export type UsersPermissionsPostRoles200 = {
  ok: boolean;
};

export type UsersPermissionsPutRolesByRoleBodyPermissions = {
  [key: string]: unknown;
};

export type UsersPermissionsPutRolesByRoleBody = {
  name?: string;
  description?: string;
  type?: string;
  permissions?: UsersPermissionsPutRolesByRoleBodyPermissions;
};

export type UsersPermissionsPutRolesByRole200 = {
  ok: boolean;
};

export type UsersPermissionsDeleteRolesByRole200 = {
  ok: boolean;
};

export type UsersPermissionsGetPermissions200PermissionsControllers = {
  [key: string]: {
    [key: string]: {
      enabled: boolean;
      policy: string;
    };
  };
};

export type UsersPermissionsGetPermissions200Permissions = {
  [key: string]: {
    controllers: UsersPermissionsGetPermissions200PermissionsControllers;
  };
};

export type UsersPermissionsGetPermissions200 = {
  permissions: UsersPermissionsGetPermissions200Permissions;
};
