/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * learning-strapi-v-5
 * API documentation for learning-strapi-v-5 v0.1.0
 * OpenAPI spec version: 0.1.0
 */
import type { I18nGetLocales200Item } from "../learningStrapiV5.schemas";

import { strapiClient } from "../../../lib/strapi-client";

export const getI18n = () => {
  const i18nGetLocales = () => {
    return strapiClient<I18nGetLocales200Item[]>({
      url: `/locales`,
      method: "GET",
    });
  };
  return { i18nGetLocales };
};
export type I18nGetLocalesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getI18n>["i18nGetLocales"]>>
>;
